import json
import os

# Create 20 high quality, authentic sentences per CEFR level (A1 to C2) = 120 rich sentences
sentences_by_level = {
  "A1": [
    ("She drinks a glass of warm water every morning.", "Cô ấy uống một ly nước ấm vào mỗi buổi sáng.", "S + V(s/es) + Object + Time (Hiện tại đơn thói quen)", [("She", "Chủ ngữ ngôi thứ ba số ít (Subject)"), ("drinks", "Động từ thêm -s theo ngôi She (Verb)"), ("a glass of warm water", "Tân ngữ trực tiếp (Direct Object)"), ("every morning", "Trạng từ chỉ thời gian thường nhật (Time Adverbial)")], "Daily Routine"),
    ("My father works at a central hospital in the city.", "Bố tôi làm việc tại một bệnh viện trung tâm trong thành phố.", "S + V(s/es) + Place Prepositions", [("My father", "Cụm danh từ làm chủ ngữ (Subject)"), ("works", "Động từ chia số ít theo ngôi He (Verb)"), ("at a central hospital", "Cụm giới từ chỉ địa điểm công tác (Place)"), ("in the city", "Cụm giới từ bổ nghĩa vị trí (Location)")], "Family & Work"),
    ("There are four modern computers on the wooden desk.", "Có bốn chiếc máy tính hiện đại ở trên bàn gỗ.", "There + are + Plural Noun + Place (Cấu trúc tồn tại số nhiều)", [("There are", "Cấu trúc chỉ sự tồn tại số nhiều (Plural Existential)"), ("four modern computers", "Danh từ số nhiều làm chủ ngữ thực (Plural Subject)"), ("on the wooden desk", "Cụm giới từ chỉ vị trí trên bề mặt (Place)")], "Objects & Home"),
    ("He can speak English and Vietnamese very fluently.", "Anh ấy có thể nói tiếng Anh và tiếng Việt rất trôi chảy.", "S + can + V-bare + Objects + Manner (Khả năng)", [("He", "Chủ ngữ (Subject)"), ("can speak", "Động từ khuyết thiếu can + động từ nguyên mẫu"), ("English and Vietnamese", "Tân ngữ kép (Objects)"), ("very fluently", "Trạng từ chỉ thể cách (Manner Adverb)")], "Ability & Language"),
    ("They do not like eating fast food for dinner.", "Họ không thích ăn thức ăn nhanh cho bữa tối.", "S + do not + V-bare + Gerund (Phủ định hiện tại đơn)", [("They", "Chủ ngữ số nhiều (Subject)"), ("do not like", "Trợ động từ phủ định + Động từ chính (Auxiliary + Verb)"), ("eating fast food", "Danh động từ V-ing làm tân ngữ (Gerund Object)"), ("for dinner", "Giới từ chỉ mục đích bữa ăn (Purpose)")], "Food & Habits"),
    ("Listen carefully because the teacher is speaking right now.", "Hãy lắng nghe cẩn thận vì cô giáo đang nói ngay bây giờ.", "Imperative + Conjunction + S + is V-ing (Mệnh lệnh + Hiện tại tiếp diễn)", [("Listen carefully", "Câu mệnh lệnh trực tiếp (Imperative)"), ("because", "Liên từ chỉ nguyên nhân (Conjunction)"), ("the teacher is speaking", "Hiện tại tiếp diễn chỉ hành động đang diễn ra"), ("right now", "Trạng từ chỉ thời điểm tức thời (Time)")], "Classroom"),
    ("What time does your first morning class start?", "Tiết học buổi sáng đầu tiên của bạn bắt đầu lúc mấy giờ?", "Wh-word + does + S + V-bare? (Câu hỏi thời gian)", [("What time", "Từ để hỏi thời gian cụ thể (Question Word)"), ("does", "Trợ động từ số ít (Auxiliary Verb)"), ("your first morning class", "Cụm danh từ chủ ngữ (Subject)"), ("start", "Động từ nguyên mẫu (Base Verb)")], "Schedule"),
    ("I usually walk to the public library on sunny afternoons.", "Tôi thường đi bộ đến thư viện công cộng vào những buổi chiều nắng ráo.", "S + Adverb of Frequency + V + Direction + Time", [("I", "Chủ ngữ (Subject)"), ("usually walk", "Trạng từ tần suất đứng trước động từ thường"), ("to the public library", "Cụm giới từ chỉ hướng đi (Direction)"), ("on sunny afternoons", "Cụm trạng từ chỉ thời gian (Time)")], "Habits"),
    ("We have two friendly dogs and a little white cat.", "Chúng tôi có hai chú chó thân thiện và một chú mèo trắng nhỏ.", "S + have + Objects (Động từ sở hữu)", [("We have", "Chủ ngữ số nhiều + Động từ sở hữu (Have)"), ("two friendly dogs", "Cụm tân ngữ thứ nhất có tính từ bổ nghĩa"), ("and", "Liên từ nối bổ sung (Conjunction)"), ("a little white cat", "Cụm tân ngữ thứ hai (Object 2)")], "Pets & Home"),
    ("Please close the window before you go to sleep.", "Làm ơn hãy đóng cửa sổ trước khi bạn đi ngủ.", "Polite Imperative + Time Clause (Lời đề nghị lịch sự)", [("Please close", "Từ lịch sự 'Please' + Động từ mệnh lệnh"), ("the window", "Tân ngữ trực tiếp (Direct Object)"), ("before you go to sleep", "Mệnh đề trạng ngữ chỉ thời gian (Time Clause)")], "Politeness"),
    ("She is wearing a beautiful blue dress today.", "Hôm nay cô ấy đang mặc một chiếc váy màu xanh dương rất đẹp.", "S + is + wearing + Adjective + Noun (Hiện tại tiếp diễn miêu tả trang phục)", [("She is wearing", "Hiện tại tiếp diễn miêu tả trang phục đang mặc trên người"), ("a beautiful blue dress", "Cụm danh từ tân ngữ với trật tự tính từ Opinion + Color"), ("today", "Trạng từ thời gian (Time)")], "Clothing"),
    ("My brother does not drink coffee late at night.", "Anh trai tôi không uống cà phê muộn vào ban đêm.", "S + does not + V-bare + Time (Phủ định ngôi thứ 3 số ít)", [("My brother", "Chủ ngữ số ít ngôi He (Subject)"), ("does not drink", "Phủ định với trợ động từ does not"), ("coffee", "Danh từ không đếm được làm tân ngữ (Object)"), ("late at night", "Cụm từ chỉ thời điểm đêm muộn (Time)")], "Health & Routine"),
    ("How much does this new English dictionary cost?", "Cuốn từ điển tiếng Anh mới này có giá bao nhiêu?", "How much + does + S + cost? (Câu hỏi giá cả)", [("How much", "Cụm từ để hỏi về giá tiền (Price Question)"), ("does ... cost", "Động từ cost đi cùng trợ động từ does"), ("this new English dictionary", "Cụm danh từ chủ ngữ (Subject)")], "Shopping"),
    ("They always eat lunch together at twelve o'clock.", "Họ luôn luôn ăn trưa cùng nhau vào lúc mười hai giờ đúng.", "S + always + V + O + Manner + Time (Thói quen giờ giấc)", [("They always eat", "Chủ ngữ + Trạng từ tần suất tuyệt đối (Always) + Động từ"), ("lunch", "Tân ngữ chỉ bữa ăn (Object)"), ("together", "Trạng từ chỉ sự gắn kết (Manner)"), ("at twelve o'clock", "Giới từ 'at' đi với giờ chính xác (Clock Time)")], "Daily Life"),
    ("Is your sister a university student in Hanoi?", "Chị gái của bạn có phải là sinh viên đại học ở Hà Nội không?", "Am/Is/Are + S + Noun Phrase? (Câu hỏi Yes/No với To Be)", [("Is", "Động từ To Be đảo lên đầu câu hỏi"), ("your sister", "Chủ ngữ ngôi thứ 3 số ít (Subject)"), ("a university student", "Cụm bổ ngữ chỉ danh phận/nghề nghiệp (Complement)"), ("in Hanoi", "Giới từ chỉ địa danh thành phố (Place)")], "Questions"),
    ("Where do you buy these fresh tropical fruits?", "Bạn mua những loại trái cây nhiệt đới tươi ngon này ở đâu vậy?", "Where + do + S + V-bare + Object? (Câu hỏi nơi chốn)", [("Where", "Từ để hỏi về địa điểm (Where)"), ("do you buy", "Trợ động từ do + Chủ ngữ you + Động từ buy"), ("these fresh tropical fruits", "Cụm danh từ chỉ thị số nhiều làm tân ngữ") ], "Market & Food"),
    ("He reads thirty minutes of English news every evening.", "Anh ấy đọc ba mươi phút tin tức tiếng Anh vào mỗi buổi tối.", "S + V(s) + Duration of Noun + Time (Hành động lặp lại)", [("He reads", "Chủ ngữ số ít + Động từ thêm -s"), ("thirty minutes of English news", "Cụm danh từ định lượng chỉ nội dung đọc"), ("every evening", "Trạng từ thời gian định kỳ (Time Adverbial)")], "Study Habits"),
    ("The weather is very warm and sunny this weekend.", "Thời tiết cuối tuần này rất ấm áp và có nhiều nắng.", "S + is + Degree Adverb + Adjectives + Time", [("The weather", "Chủ ngữ chỉ thời tiết (Subject)"), ("is", "Liên động từ To Be (Linking Verb)"), ("very warm and sunny", "Trạng từ chỉ mức độ 'very' + Hai tính từ nối bởi 'and'"), ("this weekend", "Trạng từ chỉ thời gian cuối tuần (Time)")], "Weather"),
    ("Can you help me carry this heavy luggage, please?", "Bạn có thể làm ơn giúp tôi xách kiện hành lý nặng này được không?", "Can you + V-bare + Object + V-bare? (Lời nhờ vả lịch sự)", [("Can you help me", "Cấu trúc đề nghị giúp đỡ lịch sự (Polite Request)"), ("carry this heavy luggage", "Động từ nguyên mẫu theo sau tân ngữ của help"), ("please", "Từ đệm thể hiện phép lịch sự tối đa")], "Travel & Courtesy"),
    ("We are very proud of our friendly school teachers.", "Chúng tôi rất tự hào về các thầy cô giáo thân thiện của trường mình.", "S + are + proud of + Noun Phrase (Cụm tính từ đi với giới từ)", [("We are", "Chủ ngữ số nhiều + Động từ To Be"), ("very proud of", "Cụm tính từ cố định: be proud of (tự hào về)"), ("our friendly school teachers", "Cụm danh từ tân ngữ của giới từ of")], "Education")
  ],

  "A2": [
    ("Last night, we watched an interesting documentary about space exploration.", "Tối qua, chúng tôi đã xem một bộ phim tài liệu thú vị về thám hiểm không gian.", "Past Simple Narrative (Kể chuyện quá khứ)", [("Last night", "Trạng ngữ chỉ thời gian trong quá khứ"), ("we watched", "Chủ ngữ + Động từ có quy tắc đuôi -ed"), ("an interesting documentary", "Tân ngữ có tính từ đuôi -ing miêu tả vật"), ("about space exploration", "Giới từ about chỉ chủ đề")], "Entertainment"),
    ("Taking the train is much faster and cheaper than flying by airplane.", "Đi tàu hỏa nhanh hơn và rẻ hơn nhiều so với việc bay bằng máy bay.", "Gerund Subject + Comparative Adjectives with Much", [("Taking the train", "Danh động từ V-ing đóng vai trò chủ ngữ số ít"), ("is", "Động từ to be số ít"), ("much faster and cheaper", "So sánh hơn dùng 'much' để nhấn mạnh chênh lệch"), ("than flying by airplane", "Đối tượng được so sánh")], "Travel & Transport"),
    ("While I was cooking dinner, my phone suddenly rang twice.", "Trong khi tôi đang nấu bữa tối, điện thoại của tôi bỗng nhiên reo lên hai lần.", "While + Past Continuous, Past Simple (Hành động bị cắt ngang)", [("While I was cooking dinner", "Mệnh đề quá khứ tiếp diễn chỉ hành động đang diễn ra"), ("my phone suddenly rang", "Mệnh đề quá khứ đơn chỉ hành động bất ngờ chen ngang"), ("twice", "Trạng từ chỉ số lần")], "Narrative"),
    ("If the weather is fine tomorrow, we are going to have a picnic by the lake.", "Nếu ngày mai thời tiết đẹp, chúng tôi dự định sẽ đi dã ngoại bên bờ hồ.", "If + Present Simple, be going to (Dự định có điều kiện)", [("If the weather is fine tomorrow", "Mệnh đề điều kiện có thể xảy ra"), ("we are going to have a picnic", "Cấu trúc be going to chỉ kế hoạch đã dự tính"), ("by the lake", "Cụm giới từ chỉ địa điểm")], "Plans & Weather"),
    ("You should visit the doctor if your dry cough continues for three days.", "Bạn nên đi khám bác sĩ nếu cơn ho khan kéo dài suốt ba ngày.", "Modal Advice: S + should + V-bare + Condition", [("You should visit the doctor", "Cấu trúc khuyên bảo mang tính chất y tế"), ("if your dry cough continues", "Mệnh đề điều kiện thực tế ở hiện tại"), ("for three days", "Giới từ for chỉ khoảng thời gian kéo dài")], "Health Advice"),
    ("She has lived in this peaceful coastal town since she was a little child.", "Cô ấy đã sống ở thị trấn ven biển yên bình này kể từ khi còn là một đứa trẻ.", "Present Perfect with Since (Hành động bắt đầu từ quá khứ kéo dài đến hiện tại)", [("She has lived", "Thì Hiện tại hoàn thành (has + V3)"), ("in this peaceful coastal town", "Cụm giới từ chỉ nơi chốn"), ("since she was a little child", "Mệnh đề thời gian với 'since' chia ở quá khứ đơn")], "Present Perfect"),
    ("I used to ride my bicycle to primary school every single morning.", "Tôi từng thường xuyên đạp xe đạp tới trường tiểu học vào mỗi buổi sáng.", "S + used to + V-bare (Thói quen trong quá khứ nay không còn)", [("I used to ride", "Cấu trúc used to diễn tả thói quen quá khứ đã chấm dứt"), ("my bicycle", "Tân ngữ trực tiếp"), ("to primary school", "Nơi chốn hướng tới"), ("every single morning", "Nhấn mạnh tính lặp lại định kỳ trong quá khứ")], "Past Habits"),
    ("Could you please tell me the quickest way to the central railway station?", "Bạn có thể làm ơn chỉ cho tôi con đường nhanh nhất đến ga xe lửa trung tâm được không?", "Polite Request with Superlative Adjective", [("Could you please tell me", "Lời đề nghị gián tiếp lịch sự với Could"), ("the quickest way", "So sánh nhất của tính từ ngắn (the -est)"), ("to the central railway station", "Địa điểm cần tới")], "Directions"),
    ("This jacket is not warm enough to wear during freezing winter days.", "Chiếc áo khoác này không đủ ấm để mặc trong những ngày mùa đông băng giá.", "Adj + enough + to-V (Cấu trúc chỉ mức độ đủ/không đủ)", [("This jacket is not", "Chủ ngữ + To Be phủ định"), ("warm enough", "Tính từ đứng TRƯỚC 'enough'"), ("to wear", "Động từ nguyên mẫu có to"), ("during freezing winter days", "Cụm giới từ chỉ thời điểm mùa đông")], "Clothing & Weather"),
    ("They arrived at the international airport too late to catch their scheduled flight.", "Họ đã đến sân bay quốc tế quá muộn để có thể kịp chuyến bay theo lịch trình.", "Too + Adverb + to-V (Quá... đến nỗi không thể làm gì)", [("They arrived at the international airport", "Mệnh đề quá khứ đơn diễn tả sự việc đã xảy ra"), ("too late", "Trạng từ đi sau 'too' mang nghĩa tiêu cực quá mức"), ("to catch their scheduled flight", "Hành động bị ngăn trở không thực hiện được")], "Travel Delays"),
    ("Because the bus was crowded, he decided to walk home on foot.", "Bởi vì xe buýt quá đông người, anh ấy đã quyết định đi bộ về nhà.", "Because Clause + S + decided to-V (Mệnh đề chỉ lý do)", [("Because the bus was crowded", "Mệnh đề phụ chỉ nguyên nhân với liên từ Because"), ("he decided", "Chủ ngữ và động từ mệnh đề chính"), ("to walk home on foot", "Cụm chỉ phương thức đi lại bằng chân")], "Commuting"),
    ("Have you ever traveled to an English-speaking country before?", "Bạn đã từng đi du lịch tới một quốc gia nói tiếng Anh bao giờ chưa?", "Have + S + ever + V3? (Trải nghiệm trong đời)", [("Have you ever traveled", "Thì Hiện tại hoàn thành dùng 'ever' hỏi về trải nghiệm"), ("to an English-speaking country", "Tính từ ghép (Compound Adjective: English-speaking)"), ("before", "Trạng từ nhấn mạnh 'trước đây'")], "Experience"),
    ("He is much more interested in history than in mathematics.", "Anh ấy hứng thú với môn lịch sử nhiều hơn nhiều so với môn toán học.", "Comparative of Adjectives with Preposition (be interested in)", [("He is much more interested in", "So sánh hơn của tính từ dài kết hợp giới từ 'in'"), ("history", "Đối tượng quan tâm thứ nhất"), ("than in mathematics", "Đối tượng so sánh thứ hai")], "Interests"),
    ("Don't forget to lock the front door when you leave the apartment.", "Đừng quên khóa cửa trước khi bạn rời khỏi căn hộ nhé.", "Don't forget + to-V + Time Clause (Lời nhắc nhở)", [("Don't forget to lock", "Cấu trúc nhắc nhở làm việc bổn phận: forget + to-V"), ("the front door", "Tân ngữ"), ("when you leave the apartment", "Mệnh đề thời gian chia Hiện tại đơn mang ý nghĩa tương lai")], "Safety"),
    ("The novel was so captivating that I finished it in a single day.", "Cuốn tiểu thuyết cuốn hút đến nỗi tôi đã đọc xong nó chỉ trong vỏn vẹn một ngày.", "So + Adjective + that Clause (Quá... đến nỗi mà)", [("The novel was so captivating", "Tính từ captivating miêu tả sức lôi cuốn mạnh mẽ"), ("that", "Liên từ mở đầu mệnh đề kết quả"), ("I finished it in a single day", "Kết quả tất yếu xảy ra")], "Reading"),
    ("We need to buy some fresh vegetables, but we don't need any meat.", "Chúng tôi cần mua một ít rau tươi, nhưng chúng tôi không cần chút thịt nào.", "Some (khẳng định) vs Any (phủ định)", [("We need to buy some fresh vegetables", "Dùng 'some' trong câu khẳng định với danh từ số nhiều"), ("but", "Liên từ đối lập"), ("we don't need any meat", "Dùng 'any' trong câu phủ định với danh từ không đếm được")], "Quantifiers"),
    ("She was born on the fifteenth of August in a small seaside village.", "Cô ấy sinh vào ngày mười lăm tháng tám tại một ngôi làng nhỏ ven biển.", "Preposition: On with dates, In with places", [("She was born", "Cấu trúc bị động chỉ ngày sinh"), ("on the fifteenth of August", "Giới từ 'on' dùng cho ngày cụ thể có thứ tự"), ("in a small seaside village", "Giới từ 'in' dùng cho địa hạt làng xã")], "Biography"),
    ("I am looking forward to seeing my old classmates again next month.", "Tôi đang rất mong chờ được gặp lại các bạn học cũ vào tháng tới.", "Look forward to + V-ing (Cấu trúc mong đợi)", [("I am looking forward to", "Thì Hiện tại tiếp diễn với cụm động từ look forward to"), ("seeing my old classmates", "Bắt buộc đi với Danh động từ V-ing sau giới từ 'to'"), ("again next month", "Trạng từ thời gian tương lai")], "Reunion"),
    ("He speaks English well, but his sister speaks even more naturally.", "Anh ấy nói tiếng Anh giỏi, nhưng em gái anh ấy nói còn tự nhiên hơn nữa.", "Adverb Comparison with Even", [("He speaks English well", "Trạng từ 'well' bổ nghĩa cho động từ speaks"), ("but", "Liên từ chỉ sự so sánh tăng cấp"), ("his sister speaks even more naturally", "Dùng 'even' nhấn mạnh mức độ vượt trội trong so sánh hơn")], "Language Comparison"),
    ("It took him nearly three hours to finish his science homework.", "Anh ấy đã mất gần ba tiếng đồng hồ để hoàn thành bài tập khoa học.", "It took + Person + Time + to-V (Cấu trúc tiêu tốn thời gian)", [("It took him", "Chủ ngữ giả 'It' + Động từ quá khứ took + Đại từ tân ngữ"), ("nearly three hours", "Khoảng thời gian ước lượng"), ("to finish his science homework", "Hành động tiêu tốn thời gian")], "Study Time")
  ],

  "B1": [
    ("Although she felt exhausted after work, she decided to attend the evening English workshop.", "Mặc dù cảm thấy kiệt sức sau giờ làm, cô ấy vẫn quyết định tham dự buổi hội thảo tiếng Anh buổi tối.", "Although + Concession Clause, Main Clause (Mệnh đề nhượng bộ)", [("Although she felt exhausted after work", "Mệnh đề chỉ sự nhượng bộ tương phản"), ("she decided", "Mệnh đề chính"), ("to attend the evening English workshop", "Cụm to-V làm tân ngữ chỉ quyết định")], "Perseverance"),
    ("The young software engineer who designed this mobile application won an international award.", "Kỹ sư phần mềm trẻ tuổi - người đã thiết kế ứng dụng di động này - đã đạt một giải thưởng quốc tế.", "Subject + Defining Relative Clause (who) + Main Verb + Object", [("The young software engineer", "Tiền từ đóng vai trò chủ ngữ chính"), ("who designed this mobile application", "Mệnh đề quan hệ xác định thay thế cho người"), ("won an international award", "Vị ngữ chính của toàn câu")], "Technology & Awards"),
    ("Solar panels have been installed on the rooftop to generate sustainable electricity.", "Các tấm pin năng lượng mặt trời đã được lắp đặt trên mái nhà để tạo ra nguồn điện bền vững.", "Present Perfect Passive: have been + V3 + to-V of purpose", [("Solar panels", "Chủ ngữ chịu tác động"), ("have been installed", "Bị động thì Hiện tại hoàn thành nhấn mạnh kết quả hiện hữu"), ("on the rooftop", "Nơi chốn"), ("to generate sustainable electricity", "Chỉ mục đích hành động")], "Green Energy"),
    ("If I had more leisure time, I would learn how to play the classical guitar.", "Nếu tôi có nhiều thời gian rảnh rỗi hơn, tôi sẽ học cách chơi đàn guitar cổ điển.", "Second Conditional: If + Past Simple, would + V-bare (Giả định không có thật ở hiện tại)", [("If I had more leisure time", "Mệnh đề điều kiện giả định trái với thực tế hiện tại"), ("I would learn", "Mệnh đề chính chỉ hệ quả giả định"), ("how to play the classical guitar", "Cụm danh từ chỉ kỹ năng")], "Hypothetical"),
    ("She suggested that we should organize a study group to prepare for the upcoming exam.", "Cô ấy đề xuất rằng chúng tôi nên tổ chức một nhóm học tập để chuẩn bị cho kỳ thi sắp tới.", "Subjunctive / Suggest that + S + (should) + V-bare", [("She suggested that", "Động từ gợi ý mở đầu mệnh đề đề xuất"), ("we should organize a study group", "Cấu trúc khuyên nghị với should + V nguyên mẫu"), ("to prepare for the upcoming exam", "Chỉ mục đích")], "Study Strategy"),
    ("He asked me whether I had ever worked in an international corporate environment.", "Anh ấy đã hỏi tôi liệu tôi đã từng làm việc trong môi trường tập đoàn quốc tế bao giờ chưa.", "Reported Question: asked + if/whether + S + Past Perfect", [("He asked me", "Mệnh đề tường thuật câu hỏi"), ("whether", "Từ nối trong câu hỏi Yes/No gián tiếp"), ("I had ever worked", "Lùi thì từ Hiện tại hoàn thành về Quá khứ hoàn thành"), ("in an international corporate environment", "Nơi chốn")], "Job Interviews"),
    ("In spite of the heavy rain, the outdoor music concert continued without any interruptions.", "Bất chấp cơn mưa nặng hạt, buổi hòa nhạc ngoài trời vẫn tiếp tục mà không có sự gián đoạn nào.", "In spite of + Noun Phrase, Main Clause (Nhượng bộ với cụm danh từ)", [("In spite of the heavy rain", "Cụm giới từ nhượng bộ đi kèm cụm danh từ"), ("the outdoor music concert continued", "Mệnh đề chính diễn tả sự kiên trì"), ("without any interruptions", "Cụm giới từ chỉ thể cách")], "Resilience"),
    ("The manager was satisfied with the comprehensive report that the intern had prepared.", "Người quản lý đã rất hài lòng với bản báo cáo toàn diện mà bạn thực tập sinh đã chuẩn bị.", "be satisfied with + Noun + Past Perfect Relative Clause", [("The manager was satisfied with", "Cụm tính từ đi kèm giới từ: satisfied with"), ("the comprehensive report", "Danh từ được bổ nghĩa"), ("that the intern had prepared", "Hành động chuẩn bị diễn ra TRƯỚC thời điểm hài lòng nên chia Quá khứ hoàn thành")], "Workplace"),
    ("Not only is reading books relaxing, but it also broadens your vocabulary significantly.", "Đọc sách không chỉ mang lại cảm giác thư giãn, mà nó còn mở rộng vốn từ vựng của bạn một cách đáng kể.", "Correlative Conjunctions: Not only... but also (Liên từ tương quan)", [("Not only is reading books relaxing", "Đảo ngữ nhẹ với To Be khi Not only đứng đầu câu"), ("but it also broadens", "Vế bổ sung giá trị gia tăng"), ("your vocabulary significantly", "Tân ngữ và trạng từ mức độ")], "Reading Benefits"),
    ("You had better review all irregular verbs before taking the grammar assessment.", "Tốt hơn hết là bạn nên ôn lại toàn bộ các động từ bất quy tắc trước khi làm bài kiểm tra ngữ pháp.", "S + had better + V-bare (Lời cảnh báo / khuyên nhủ khẩn thiết)", [("You had better review", "Had better mang tính khuyên răn mạnh mẽ tương đương ought to"), ("all irregular verbs", "Tân ngữ"), ("before taking the grammar assessment", "Giới từ before đi kèm V-ing")], "Grammar Review"),
    ("Neither the teacher nor the students were aware of the sudden schedule change.", "Cả giáo viên lẫn các bạn học sinh đều không hay biết về sự thay đổi lịch trình đột ngột.", "Neither... nor (Sự hòa hợp chủ ngữ - động từ gần nhất)", [("Neither the teacher nor the students", "Cấu trúc phủ định song hành: Động từ chia theo chủ ngữ gần nhất 'the students' (số nhiều)"), ("were aware of", "Tính từ aware đi kèm giới từ of"), ("the sudden schedule change", "Tân ngữ")], "Subject-Verb Agreement"),
    ("By the time the rescue team arrived, the local villagers had already put out the fire.", "Vào thời điểm đội cứu hộ tới nơi, dân làng địa phương đã dập tắt đám cháy từ trước đó rồi.", "By the time + Past Simple, Past Perfect (Hành động hoàn tất trước một mốc quá khứ)", [("By the time the rescue team arrived", "Mốc thời gian trong quá khứ xác định"), ("the local villagers had already put out the fire", "Hành động dập lửa hoàn thành TRƯỚC nên chia Quá khứ hoàn thành")], "Past Sequences"),
    ("She speaks so softly that people in the back row can hardly hear her voice.", "Cô ấy nói khẽ đến nỗi những người ở hàng ghế sau hầu như không thể nghe thấy giọng cô ấy.", "So + Adverb + that Clause with Hardly", [("She speaks so softly", "Trạng từ chỉ thể cách đi sau 'so'"), ("that", "Liên từ dẫn tới hệ quả"), ("people in the back row can hardly hear her voice", "Hardly mang nghĩa bán phủ định: hầu như không")], "Communication"),
    ("This educational software allows students to practice pronunciation at their own pace.", "Phần mềm giáo dục này cho phép học sinh luyện tập phát âm theo tốc độ riêng của từng người.", "S + allow + Object + to-V (Cho phép ai làm gì)", [("This educational software allows", "Chủ ngữ số ít đi kèm động từ allow"), ("students", "Tân ngữ trực tiếp"), ("to practice pronunciation", "Động từ nguyên mẫu có to theo sau allow"), ("at their own pace", "Thành ngữ: theo nhịp độ tự nhiên của bản thân")], "EdTech"),
    ("Unless you practice speaking English aloud daily, you will not build conversational fluency.", "Trừ phi bạn luyện nói tiếng Anh thành tiếng mỗi ngày, bạn sẽ không xây dựng được sự trôi chảy khi giao tiếp.", "Unless (= If not) + Present Simple, Future Simple", [("Unless you practice speaking English aloud daily", "Unless tương đương với If you do not practice"), ("you will not build conversational fluency", "Mệnh đề chính ở thì Tương lai đơn chỉ hệ quả tiêu cực")], "Fluency Advice"),
    ("He works as a financial consultant, which requires extraordinary attention to detail.", "Anh ấy làm việc với tư cách một cố vấn tài chính, điều này đòi hỏi sự chú ý tỉ mỉ đến từng chi tiết.", "Non-defining Relative Clause with Which referring to the whole clause", [("He works as a financial consultant", "Mệnh đề độc lập chỉ nghề nghiệp"), (", which requires", "Đại từ quan hệ 'which' thay thế cho toàn bộ sự việc ở mệnh đề trước"), ("extraordinary attention to detail", "Cụm danh từ phẩm chất nghề nghiệp")], "Professional Skills"),
    ("We were about to leave the office when an urgent client email arrived.", "Chúng tôi suýt nữa thì rời văn phòng thì một email khẩn cấp từ khách hàng gửi tới.", "be about to + V-bare (Sắp sửa làm gì thì sự việc khác xảy ra)", [("We were about to leave the office", "Cấu trúc be about to diễn tả ý định sắp thực hiện ngay tức khắc"), ("when", "Từ nối thời điểm"), ("an urgent client email arrived", "Sự việc quá khứ bất ngờ xảy đến")], "Work Interruptions"),
    ("The more you immerse yourself in English podcasts, the more natural your intonation becomes.", "Bạn càng đắm mình vào các tập podcast tiếng Anh, ngữ điệu của bạn càng trở nên tự nhiên.", "The more + Clause, The more + Clause (So sánh kép càng... thì càng...)", [("The more you immerse yourself in English podcasts", "Vế điều kiện tăng tiến mức độ thẩm thấu"), ("the more natural your intonation becomes", "Vế hệ quả tăng tiến tương ứng về ngữ điệu")], "Immersion Method"),
    ("Despite having little formal training, he delivered an impressive presentation.", "Mặc dù có rất ít sự đào tạo bài bản, anh ấy vẫn trình bày một bài thuyết trình đầy ấn tượng.", "Despite + Gerund Phrase, Main Clause", [("Despite having little formal training", "Despite đi kèm danh động từ having và lượng từ little"), ("he delivered an impressive presentation", "Vị ngữ quá khứ đơn thể hiện thành tựu bất ngờ")], "Public Speaking"),
    ("It is essential that every candidate submit their certified documents before Friday.", "Điều cốt yếu là mọi ứng viên đều phải nộp các giấy tờ chứng thực của họ trước thứ Sáu.", "Present Subjunctive: It is essential that + S + V-bare", [("It is essential that", "Cấu trúc giả định thể hiện tính cấp thiết"), ("every candidate submit", "Động từ 'submit' giữ nguyên thể không chia -s dù chủ ngữ là số ít"), ("their certified documents before Friday", "Tân ngữ và mốc thời gian")], "Formal Requirements")
  ],

  "B2": [
    ("Having analyzed the statistical data thoroughly, the committee recommended immediate financial reform.", "Sau khi đã phân tích kỹ lưỡng các số liệu thống kê, ủy ban đã đề xuất cải cách tài chính ngay lập tức.", "Perfect Participle Clause (Having + V3) expressing sequence", [("Having analyzed the statistical data thoroughly", "Phân từ hoàn thành nhấn mạnh hành động phân tích đã xong trước khi đề xuất"), ("the committee", "Chủ ngữ chung"), ("recommended immediate financial reform", "Vị ngữ chính")], "Analysis"),
    ("He must have forgotten his security badge because he was unable to unlock the office door.", "Hẳn là anh ấy đã quên thẻ an ninh của mình vì anh ấy đã không thể mở khóa cửa văn phòng.", "Modal of Deduction in the Past: must have + V3", [("He must have forgotten his security badge", "Suy đoán quá khứ chắc chắn có bằng chứng xác đáng"), ("because he was unable to unlock the office door", "Căn cứ thực tế chứng minh cho suy đoán")], "Deduction"),
    ("The project would have succeeded if both departments had communicated more transparently from the beginning.", "Dự án lẽ ra đã thành công nếu cả hai phòng ban giao tiếp minh bạch hơn ngay từ đầu.", "Third Conditional: would have + V3, If + Past Perfect", [("The project would have succeeded", "Giả định kết quả trái ngược với quá khứ"), ("if both departments had communicated", "Điều kiện trong quá khứ đã không diễn ra"), ("more transparently from the beginning", "Thể cách")], "Past Reflection"),
    ("So volatile was the international market that several investment firms suspended trading.", "Thị trường quốc tế biến động mạnh đến nỗi một vài công ty đầu tư đã phải tạm ngừng giao dịch.", "Inversion with So + Adjective + be + Subject + that Clause", [("So volatile was the international market", "Đảo ngữ đưa So + Adj lên đầu câu để tối đa hóa sắc thái nhấn mạnh"), ("that several investment firms suspended trading", "Mệnh đề chỉ kết quả chấn động")], "Market Dynamics"),
    ("Were it not for your invaluable mentorship, I would not be occupying this leadership position today.", "Nếu không nhờ có sự chỉ bảo vô giá của bạn, ngày nay tôi đã không thể ngồi ở vị trí lãnh đạo này.", "Mixed Conditional Inversion: Were it not for + Noun, would be V-ing", [("Were it not for your invaluable mentorship", "Đảo ngữ câu điều kiện loại 2: Were it not for (Nếu không có)"), ("I would not be occupying this leadership position today", "Kết quả ở hiện tại kết hợp từ điều kiện quá khứ")], "Mixed Conditionals"),
    ("Under no circumstances should confidential customer data be disclosed to unauthorized third parties.", "Trong bất kỳ hoàn cảnh nào, dữ liệu khách hàng bảo mật cũng không được phép tiết lộ cho bên thứ ba.", "Negative Inversion: Under no circumstances + Modal + Subject + Passive Verb", [("Under no circumstances", "Cụm phủ định tuyệt đối đứng đầu câu"), ("should confidential customer data be disclosed", "Đảo trợ động từ should lên trước chủ ngữ bị động"), ("to unauthorized third parties", "Đối tượng bị nghiêm cấm")], "Data Privacy"),
    ("No sooner had the keynote speech concluded than the symposium floor erupted into enthusiastic applause.", "Ngay khi bài diễn thuyết chính vừa kết thúc thì cả khán phòng hội thảo đã vỡ òa trong tràng pháo tay nồng nhiệt.", "No sooner had + S + V3 + than + Past Simple (Ngay khi... thì...)", [("No sooner had the keynote speech concluded", "Đảo ngữ với No sooner chia Quá khứ hoàn thành"), ("than", "Từ nối bắt buộc đi cùng No sooner"), ("the symposium floor erupted into enthusiastic applause", "Hành động kế tiếp tức thì chia Quá khứ đơn")], "Event Narration"),
    ("Hardly had we initiated the deployment process when an unforeseen technical anomaly was detected.", "Chúng tôi vừa mới bắt đầu quy trình triển khai thì một sự cố kỹ thuật bất ngờ bị phát hiện.", "Hardly had + S + V3 + when + Past Simple", [("Hardly had we initiated the deployment process", "Đảo ngữ với trạng từ Hardly"), ("when", "Từ nối bắt buộc đi cùng Hardly/Scarcely"), ("an unforeseen technical anomaly was detected", "Mệnh đề bị động quá khứ đơn")], "Software Deployment"),
    ("The CEO insisted that the audit be conducted by an independent external supervisory agency.", "Tổng giám đốc đã kiên quyết yêu cầu cuộc kiểm toán phải được thực hiện bởi một cơ quan giám sát độc lập.", "Subjunctive with Insist: insist that + S + (be) V3", [("The CEO insisted that", "Động từ chỉ ý chí mệnh lệnh mạnh mẽ"), ("the audit be conducted", "Thể giả định bị động giữ nguyên dạng 'be conducted' không chia"), ("by an independent external supervisory agency", "Chỉ tác nhân độc lập")], "Corporate Governance"),
    ("Had I known about the stringent prerequisite requirements, I would have applied for the preparatory seminar.", "Nếu tôi biết về các yêu cầu tiên quyết khắt khe đó, tôi đã nộp đơn tham gia hội thảo dự bị rồi.", "Inversion of Conditional Type 3: Had + S + V3, would have + V3", [("Had I known about the stringent prerequisite requirements", "Đảo ngữ loại bỏ liên từ 'If' đưa 'Had' lên đầu câu"), ("I would have applied for the preparatory seminar", "Mệnh đề chính giả định tiếc nuối")], "Academic Planning"),
    ("Far from acknowledging their strategic blunder, the executives attempted to shift the blame onto market trends.", "Thay vì thừa nhận sai lầm chiến lược của mình, ban điều hành lại cố gắng đổ lỗi cho xu hướng thị trường.", "Far from + Gerund, Main Subject + Verb", [("Far from acknowledging their strategic blunder", "Cấu trúc phản đề: khác xa với việc thừa nhận sai lầm"), ("the executives attempted to shift the blame", "Hành động lảng tránh trách nhiệm"), ("onto market trends", "Đối tượng bị đổ lỗi")], "Corporate Ethics"),
    ("Such was the complexity of the philosophical treatise that even seasoned scholars struggled to decipher its thesis.", "Độ phức tạp của luận thuyết triết học đó lớn đến nỗi ngay cả những học giả dày dặn kinh nghiệm cũng chật vật để giải mã luận điểm của nó.", "Inversion with Such + be + Noun + that Clause", [("Such was the complexity of the philosophical treatise", "Đảo ngữ với Such nhấn mạnh mức độ to lớn của danh từ complexity"), ("that even seasoned scholars struggled to decipher its thesis", "Mệnh đề kết quả khẳng định độ khó")], "Intellectual Rigor"),
    ("Little did the junior analyst realize that his preliminary findings would trigger a nationwide investigation.", "Nhà phân tích trẻ tuổi chẳng ngờ được rằng những phát hiện ban đầu của anh ấy lại châm ngòi cho một cuộc điều tra toàn quốc.", "Negative Inversion with Little: Little did + S + V-bare", [("Little did the junior analyst realize", "Little mang nghĩa phủ định: hoàn toàn không hề nhận ra"), ("that his preliminary findings would trigger a nationwide investigation", "Mệnh đề danh ngữ chỉ hệ quả lớn lao trong tương lai")], "Journalistic Impact"),
    ("The strategy, although initially met with fierce resistance, ultimately proved to be remarkably lucrative.", "Chiến lược này, mặc dù ban đầu vấp phải sự kháng cự dữ dội, rốt cuộc đã chứng minh là cực kỳ sinh lợi.", "Parenthetical Concession Clause within Subject and Verb", [("The strategy", "Chủ ngữ câu chính"), (", although initially met with fierce resistance,", "Mệnh đề phân từ nhượng bộ chèn giữa câu"), ("ultimately proved to be remarkably lucrative", "Vị ngữ khẳng định thành công tài chính")], "Business Strategy"),
    ("He spoke with such eloquence and conviction that none in the audience dared to contest his premise.", "Ông ấy đã phát biểu với tài hùng biện và sức thuyết phục lớn đến nỗi không ai trong khán phòng dám phản bác tiền đề của ông.", "Such + Noun Phrase + that Clause", [("He spoke with such eloquence and conviction", "Danh từ chất lượng cao đi sau such"), ("that none in the audience dared to contest his premise", "Mệnh đề kết quả tuyệt đối hóa")], "Rhetoric"),
    ("Had it not been for the prompt intervention of the paramedic team, the patient might not have survived.", "Nếu không nhờ có sự can thiệp kịp thời của đội ngũ cấp cứu, bệnh nhân có lẽ đã không thể qua khỏi.", "Inversion of Conditional 3: Had it not been for + Noun", [("Had it not been for the prompt intervention of the paramedic team", "Cấu trúc đảo ngữ kinh điển: Had it not been for (Nếu không nhờ có)"), ("the patient might not have survived", "Phán đoán khả năng sinh tồn trong quá khứ với might have")], "Emergency Medicine"),
    ("Scarcely had the international treaty been signed when border skirmishes broke out once again.", "Hiệp ước quốc tế vừa mới được ký kết xong thì những cuộc đụng độ biên giới lại bùng phát một lần nữa.", "Scarcely had + S + V3 + when + Past Simple", [("Scarcely had the international treaty been signed", "Đảo ngữ với trạng từ Scarcely diễn tả hành động vừa dứt"), ("when border skirmishes broke out once again", "Mệnh đề thời điểm hành động tiếp theo bùng nổ")], "Diplomatic History"),
    ("It is high time the administration addressed the widening disparity between urban and rural school resources.", "Đã đến lúc chính quyền phải giải quyết sự chênh lệch ngày càng nới rộng giữa các nguồn lực trường học thành thị và nông thôn.", "It is high time + S + Past Simple (Đã đến lúc cấp bách phải làm gì)", [("It is high time", "Cấu trúc giả định thể hiện tính thúc bách vượt quá thời hạn lẽ ra phải làm"), ("the administration addressed", "Động từ bắt buộc chia Quá khứ đơn (addressed) dù nói về hành động hiện tại"), ("the widening disparity", "Cụm danh từ thực trạng xã hội")], "Social Equity"),
    ("The researcher was commended not only for her empirical accuracy, but also for her intellectual integrity.", "Nhà nghiên cứu đã được biểu dương không chỉ vì độ chính xác thực nghiệm, mà còn vì sự chính trực về mặt học thuật.", "Passive with Correlative Not only... but also", [("The researcher was commended", "Động từ bị động chỉ sự khen ngợi tuyên dương"), ("not only for her empirical accuracy", "Vế bổ nghĩa thứ nhất"), ("but also for her intellectual integrity", "Vế bổ nghĩa phẩm chất cốt lõi")], "Academic Integrity"),
    ("However daunting the challenge may appear, consistent daily practice ensures eventual linguistic mastery.", "Dù thử thách có vẻ khó khăn đến mức nào đi chăng nữa, việc luyện tập kiên trì mỗi ngày cũng sẽ đảm bảo việc làm chủ ngôn ngữ cuối cùng.", "However + Adjective + S + Verb, Main Clause", [("However daunting the challenge may appear", "Mệnh đề nhượng bộ mức độ: Dù thử thách có đáng sợ đến đâu"), ("consistent daily practice", "Chủ ngữ hành động tích cực"), ("ensures eventual linguistic mastery", "Vị ngữ khẳng định kết quả chắc chắn")], "Language Mindset")
  ],

  "C1": [
    ("Not only did the keynote speaker challenge prevailing economic dogmas, but she also proposed a viable alternative.", "Không những diễn giả chính thách thức các giáo điều kinh tế hiện hành, mà bà ấy còn đề xuất một giải pháp thay thế khả thi.", "Negative Inversion: Not only did + S + V, but S also + V", [("Not only did the keynote speaker challenge", "Đảo ngữ mượn trợ động từ did nhấn mạnh hành động thách thức học thuyết"), ("prevailing economic dogmas", "Thuật ngữ học thuật chỉ các giáo điều thịnh hành"), ("but she also proposed a viable alternative", "Khẳng định đóng góp mang tính giải pháp thực tiễn")], "Economic Rhetoric"),
    ("It was her unwavering intellectual tenacity that ultimately enabled the team to crack the encryption algorithm.", "Chính sự kiên định trí tuệ không lay chuyển của cô ấy rốt cuộc đã giúp cả nhóm giải mã được thuật toán mã hóa.", "Cleft Sentence: It was + Focus Element + that + Clause", [("It was", "Mở đầu cấu trúc câu chẻ nhấn mạnh trọng tâm"), ("her unwavering intellectual tenacity", "Thành phần cốt lõi được vinh danh"), ("that ultimately enabled the team to crack the encryption algorithm", "Mệnh đề làm rõ thành tựu đạt được")], "Focus & Tenacity"),
    ("Seldom have technological disruptions reshaped human sociolinguistic paradigms with such astonishing velocity.", "Hiếm khi những sự gián đoạn công nghệ lại tái định hình các khuôn mẫu ngôn ngữ xã hội của loài người với tốc độ đáng kinh ngạc đến thế.", "Negative Adverbial Inversion: Seldom have + S + V3", [("Seldom have technological disruptions reshaped", "Đảo ngữ với trạng từ phủ định Seldom đưa trợ động từ have lên trước"), ("human sociolinguistic paradigms", "Khái niệm ngôn ngữ học xã hội"), ("with such astonishing velocity", "Cụm trạng ngữ tu từ chỉ gia tốc chấn động")], "Sociolinguistics"),
    ("Only after cross-referencing archival manuscripts for a decade did the historian dare to publish his controversial hypothesis.", "Chỉ sau khi đối chiếu chéo các bản thảo lưu trữ suốt một thập kỷ, nhà sử học mới dám xuất bản giả thuyết gây tranh cãi của mình.", "Inversion with Only after: Only after + Phrase/Clause + did + S + V-bare", [("Only after cross-referencing archival manuscripts for a decade", "Cụm điều kiện thời gian kéo dài"), ("did the historian dare to publish", "Đảo ngữ mệnh đề chính với trợ động từ did"), ("his controversial hypothesis", "Đối tượng công bố")], "Historiography"),
    ("Much as I appreciate your creative intuition, academic rigorousness demands empirical verification before we proceed.", "Dù tôi rất trân trọng trực giác sáng tạo của bạn, sự chuẩn xác học thuật vẫn đòi hỏi sự kiểm chứng thực nghiệm trước khi chúng ta tiến hành.", "Concession with Much as: Much as + S + V, Main Clause", [("Much as I appreciate your creative intuition", "Cấu trúc nhượng bộ cao cấp: Dù cho tôi đánh giá cao"), ("academic rigorousness demands", "Chủ ngữ tính chất học thuật đòi hỏi"), ("empirical verification before we proceed", "Điều kiện bắt buộc trước khi triển khai")], "Scientific Method"),
    ("So pervasive has digital hyper-connectivity become that solitude is now viewed as an elusive luxury.", "Sự siêu kết nối kỹ thuật số đã trở nên lan tỏa rộng khắp đến mức sự cô độc giờ đây bị coi là một thứ xa xỉ khó nắm bắt.", "Inversion: So + Adjective + has + S + become + that Clause", [("So pervasive has digital hyper-connectivity become", "Đảo ngữ với tính từ pervasive nhấn mạnh độ bao trùm"), ("that solitude is now viewed as an elusive luxury", "Mệnh đề hệ quả triết học hiện đại")], "Digital Philosophy"),
    ("On no account should the diplomatic envoy compromise sovereign integrity in exchange for short-term trade concessions.", "Trong bất cứ trường hợp nào, phái viên ngoại giao cũng không được phép thỏa hiệp tính toàn vẹn chủ quyền để đổi lấy các nhượng bộ thương mại ngắn hạn.", "Negative Inversion: On no account + Modal + S + V", [("On no account", "Cụm phủ định tối thượng: Tuyệt đối không vì bất kỳ lý do gì"), ("should the diplomatic envoy compromise", "Đảo trợ động từ should lên trước chủ ngữ ngoại giao"), ("sovereign integrity in exchange for short-term trade concessions", "Mối tương quan bất cân xứng")], "Diplomacy"),
    ("Were the international arbitration panel to rule in favor of the plaintiff, the precedent would alter maritime law indefinitely.", "Nếu hội đồng trọng tài quốc tế phán quyết nghiêng về phía nguyên đơn, án lệ này sẽ làm thay đổi luật hàng hải vĩnh viễn.", "Inversion of Conditional 2: Were + S + to-V, would + V-bare", [("Were the international arbitration panel to rule", "Đảo ngữ trang trọng tột bậc thay thế If the panel were to rule"), ("in favor of the plaintiff", "Phán quyết có lợi cho bên khởi kiện"), ("the precedent would alter maritime law indefinitely", "Tầm ảnh hưởng vĩ mô dài hạn")], "Jurisprudence"),
    ("What astounds me most about this classical symposium is the sheer lucidity with which ancient philosophers addressed existential angst.", "Điều làm tôi kinh ngạc nhất về hội thảo cổ điển này là sự sáng rõ tột cùng mà các triết gia cổ đại đã dùng để giải quyết nỗi âu lo hiện sinh.", "Wh-cleft Sentence: What + Verb Phrase + is + Noun Phrase", [("What astounds me most about this classical symposium", "Mệnh đề danh ngữ làm chủ ngữ tiêu điểm"), ("is", "Động từ liên kết"), ("the sheer lucidity with which ancient philosophers addressed existential angst", "Bổ ngữ học thuật tinh tế")], "Existentialism"),
    ("Scarcely had the sovereign central bank raised benchmark interest rates when currency speculators began liquidating domestic bonds.", "Ngân hàng trung ương có chủ quyền vừa mới nâng lãi suất cơ chuẩn thì các nhà đầu cơ tiền tệ đã bắt đầu thanh lý trái phiếu nội địa.", "Scarcely had + S + V3 + when + S + Past Simple", [("Scarcely had the sovereign central bank raised benchmark interest rates", "Đảo ngữ quá khứ hoàn thành với Scarcely"), ("when currency speculators began liquidating domestic bonds", "Phản ứng thị trường tài chính tức thời")], "Macro-finance"),
    ("Lest there be any misunderstanding regarding the treaty parameters, let us delineate each jurisdictional boundary unequivocally.", "Để tránh bất kỳ sự hiểu lầm nào liên quan đến các tham số hiệp ước, chúng ta hãy phân định từng ranh giới quyền tài phán một cách dứt khoát.", "Conjunctive Lest + Subjunctive (be)", [("Lest there be any misunderstanding", "Lest (vì sợ rằng / để không) đi kèm động từ nguyên mẫu giả định 'be'"), ("regarding the treaty parameters", "Phạm vi hiệp định"), ("let us delineate each jurisdictional boundary unequivocally", "Hành động phân định dứt khoát")], "Treaty Negotiations"),
    ("It is imperative that the bioethics oversight council remain fully autonomous from commercial pharmaceutical sponsors.", "Điều tối quan trọng là hội đồng giám sát đạo đức sinh học phải duy trì tính độc lập hoàn toàn khỏi các nhà tài trợ dược phẩm thương mại.", "Mandative Subjunctive: It is imperative that + S + V-bare", [("It is imperative that", "Cấu trúc giả định mệnh lệnh cấp thiết"), ("the bioethics oversight council remain fully autonomous", "Động từ 'remain' giữ nguyên mẫu không chia theo chủ ngữ số ít"), ("from commercial pharmaceutical sponsors", "Bảo vệ tính khách quan khoa học")], "Bioethics"),
    ("By virtue of her comprehensive erudition, she was unanimously appointed chair of the comparative linguistics department.", "Nhờ vào học vấn uyên thâm và toàn diện của mình, bà đã được nhất trí bổ nhiệm làm trưởng khoa ngôn ngữ học so sánh.", "Prepositional Link: By virtue of + Noun Phrase", [("By virtue of her comprehensive erudition", "Cụm giới từ chỉ lý do dựa trên năng lực vượt trội: Nhờ vào"), ("she was unanimously appointed", "Vị ngữ bị động với trạng từ đồng thuận tuyệt đối"), ("chair of the comparative linguistics department", "Chức danh học thuật cao quý")], "Academic Honors"),
    ("No sooner had the diplomatic summit adjourned than preliminary communiqués were transmitted to foreign capitals.", "Hội nghị thượng đỉnh ngoại giao vừa mới bế mạc thì các thông cáo sơ bộ đã được truyền tới các thủ đô nước ngoài.", "No sooner had + S + V3 + than + Past Passive", [("No sooner had the diplomatic summit adjourned", "Đảo ngữ No sooner với động từ bế mạc hội nghị"), ("than", "Từ nối bắt buộc"), ("preliminary communiqués were transmitted to foreign capitals", "Mệnh đề bị động quá khứ")], "Diplomatic Protocol"),
    ("Tired though the mountaineers were after ascending the jagged precipice, their spirits remained indomitable.", "Dù các nhà leo núi có mệt mỏi đến đâu sau khi trèo lên vách đá lởm chởm, tinh thần của họ vẫn bất khuất kiên cường.", "Inversion with Adjective + though/as + S + Verb", [("Tired though the mountaineers were", "Đảo tính từ Tired lên đầu câu kết hợp though"), ("after ascending the jagged precipice", "Cụm giới từ chỉ sự hiểm trở"), ("their spirits remained indomitable", "Khẳng định ý chí sắt đá")], "Indomitable Spirit"),
    ("Had the geopolitical landscape been less fractured, multilateral consensus on climate targets might have been codified decades ago.", "Nếu bối cảnh địa chính trị bớt chia rẽ hơn, sự đồng thuận đa phương về các mục tiêu khí hậu có lẽ đã được pháp chế hóa từ nhiều thập kỷ trước.", "Inversion of Conditional 3 with Modal Passive", [("Had the geopolitical landscape been less fractured", "Đảo ngữ loại 3 giả định bối cảnh địa chính trị"), ("multilateral consensus on climate targets", "Chủ ngữ danh từ ghép học thuật"), ("might have been codified decades ago", "Phỏng đoán kết quả lẽ ra đã thành luật")], "Climate Governance"),
    ("Beneath the exterior of polished decorum lay an acute intellectual rivalry that fueled decades of fierce theoretical debates.", "Bên dưới vẻ bề ngoài của lễ nghi tao nhã lại ẩn chứa một sự kình địch trí tuệ sâu sắc đã thổi bùng lên hàng thập kỷ tranh luận lý thuyết nảy lửa.", "Locative Inversion: Prepositional Phrase of Place + Verb + Subject", [("Beneath the exterior of polished decorum", "Cụm giới từ nơi chốn đảo lên đầu câu"), ("lay", "Động từ nội động từ chia quá khứ của lie"), ("an acute intellectual rivalry", "Chủ ngữ thực được đẩy ra sau động từ"), ("that fueled decades of fierce theoretical debates", "Mệnh đề quan hệ chỉ hệ quả học thuật")], "Academic Rivalry"),
    ("In no way can the author's idiosyncratic narrative architecture be regarded as conventional or derivative.", "Không đời nào lối kiến trúc tự sự mang phong cách riêng của tác giả lại có thể bị coi là rập khuôn hay sao chép.", "Negative Inversion: In no way + Modal + S + Passive Verb", [("In no way", "Cụm từ phủ định nhấn mạnh tính độc bản: Không một cách nào"), ("can the author's idiosyncratic narrative architecture be regarded", "Đảo modal can lên trước chủ ngữ phức tạp"), ("as conventional or derivative", "Bác bỏ định kiến tầm thường")], "Literary Analysis"),
    ("Such was her devotion to linguistic precision that she spent months verifying the provenance of a single archaic idiom.", "Lòng tận tụy của cô đối với sự chính xác ngôn ngữ lớn đến nỗi cô đã dành nhiều tháng chỉ để xác minh nguồn gốc của một thành ngữ cổ đơn lẻ.", "Inversion: Such was + Noun + that Clause", [("Such was her devotion to linguistic precision", "Đảo ngữ Such was nhấn mạnh mức độ tận hiến học thuật"), ("that she spent months verifying the provenance of a single archaic idiom", "Mệnh đề chứng minh tính kỹ lưỡng tỉ mỉ")], "Philology"),
    ("Hardly had the controversial legislation passed before human rights advocates filed constitutional challenges in the supreme court.", "Đạo luật gây tranh cãi vừa mới được thông qua thì các nhà bảo vệ nhân quyền đã đệ đơn khiếu nại hiến pháp lên tòa án tối cao.", "Hardly had + S + V3 + before/when Clause", [("Hardly had the controversial legislation passed", "Đảo ngữ với Hardly diễn tả đạo luật vừa lọt qua quốc hội"), ("before human rights advocates filed constitutional challenges in the supreme court", "Hành động can thiệp pháp lý tức thì")], "Constitutional Law")
  ],

  "C2": [
    ("Far from being a mere pedagogical panacea, autonomous digital immersion demands relentless cognitive discipline.", "Khác xa với việc là một phương thuốc vạn năng cho giáo dục, việc tự học kỹ thuật số đòi hỏi một kỷ luật nhận thức không ngừng nghỉ.", "Prepositional Concession: Far from + Gerund, Main Clause with Nuanced Collocation", [("Far from being a mere pedagogical panacea", "Mệnh đề tu từ bác bỏ nhận thức nông cạn về công nghệ giáo dục"), ("autonomous digital immersion", "Chủ ngữ danh từ trừu tượng học thuật cao cấp"), ("demands relentless cognitive discipline", "Kết hợp từ chuẩn xác chỉ sự kỷ luật thép")], "Pedagogical Philosophy"),
    ("Should unforeseen geopolitical volatility destabilize the currency markets, central banking authorities stand ready to intervene.", "Nếu những biến động địa chính trị khôn lường làm mất ổn định thị trường tiền tệ, các cơ quan ngân hàng trung ương luôn ở tư thế sẵn sàng can thiệp.", "Inversion of Conditional 1: Should + S + V-bare, Main Clause", [("Should unforeseen geopolitical volatility destabilize", "Đảo ngữ trang trọng thay thế cho If... should"), ("the currency markets", "Tân ngữ kinh tế vĩ mô"), ("central banking authorities stand ready to intervene", "Thành ngữ cao cấp 'stand ready to' chỉ sự sẵn sàng phản ứng")], "Macro-finance"),
    ("His trenchant polemic dismantled the established orthodoxies with an erudite precision that left his intellectual adversaries disarmed.", "Bài bút chiến đanh thép của ông đã tháo dỡ các giáo điều truyền thống với sự chuẩn xác uyên bác khiến những đối thủ học thuật của ông hoàn toàn bị vô hiệu hóa.", "Complex Narrative Clause with Literary Collocations", [("His trenchant polemic", "Chủ ngữ mang sắc thái phê phán sâu cay đanh thép"), ("dismantled the established orthodoxies", "Ẩn dụ tháo dỡ các giáo điều chính thống"), ("with an erudite precision", "Trạng ngữ chỉ phong độ học giả uyên thâm"), ("that left his intellectual adversaries disarmed", "Mệnh đề kết quả khẳng định sự thắng thế tuyệt đối")], "Literary Polemics"),
    ("Be that as it may, the philosophical treatise posits an ontological distinction between sensory perception and empirical reality.", "Dẫu cho điều đó có là như thế đi chăng nữa, luận thuyết triết học vẫn xác lập một sự phân định bản thể luận giữa tri giác cảm quan và thực tại thực nghiệm.", "Idiomatic Concession: Be that as it may + Academic Clause", [("Be that as it may", "Thành ngữ C2 diễn tả sự nhượng bộ trang trọng tương đương dù sao đi nữa"), ("the philosophical treatise posits", "Động từ học thuật posit (xác lập luận điểm)"), ("an ontological distinction between sensory perception and empirical reality", "Thuật ngữ triết học bản thể luận chuyên sâu")], "Ontology"),
    ("Only through a relentless synthesis of dialectical materialism and hermeneutic inquiry can such systemic historiographical paradoxes be resolved.", "Chỉ thông qua sự tổng hợp không ngừng giữa chủ nghĩa duy vật biện chứng và phương pháp chú giải học thì những nghịch lý sử học mang tính hệ thống như vậy mới có thể được giải quyết.", "Only through + Noun Phrase + Modal Inversion (can + S + be V3)", [("Only through a relentless synthesis of dialectical materialism and hermeneutic inquiry", "Cụm giới từ triết học đồ sộ làm tiền đề duy nhất"), ("can such systemic historiographical paradoxes be resolved", "Đảo ngữ trợ động từ can lên trước chủ ngữ bị động")], "Historiographical Theory"),
    ("Seldom if ever has a literary masterpiece woven existential weltschmerz and satirical wit into so harmonious a tapestry.", "Hiếm khi hoặc họa hoằn lắm mới có một kiệt tác văn học dệt nỗi u sầu nhân thế và sự châm biếm sâu cay vào một bức tranh hài hòa đến nhường ấy.", "Inversion with Seldom if ever + so + Adj + a + Noun", [("Seldom if ever has a literary masterpiece woven", "Đảo ngữ kép với Seldom if ever đưa trợ động từ has lên trước"), ("existential weltschmerz and satirical wit", "Sự đan xen giữa nỗi đau hiện sinh và trí tuệ trào phúng"), ("into so harmonious a tapestry", "Cấu trúc so + tính từ + mạo từ a + danh từ")], "Aesthetic Criticism"),
    ("Were posterity to judge this generation solely by its ephemeral consumerist excess, the verdict would be unsparingly severe.", "Nếu hậu thế phán xét thế hệ này chỉ dựa trên sự thừa thãi tiêu dùng phù du của nó, bản án đưa ra chắc chắn sẽ vô cùng khắc nghiệt.", "Inversion of Conditional 2: Were + S + to-V, would be + Adverb + Adj", [("Were posterity to judge this generation solely by its ephemeral consumerist excess", "Đảo ngữ điều kiện loại 2 giả định góc nhìn của hậu thế tương lai"), ("the verdict would be unsparingly severe", "Mệnh đề chính khẳng định mức độ nghiêm khắc tột cùng")], "Societal Critique"),
    ("Never in the annals of modern statecraft has a populist demagogue manipulated collective neuroses with such unabashed cynicism.", "Chưa từng có trong biên niên sử của nghệ thuật trị quốc hiện đại, một kẻ mị dân dân túy lại thao túng chứng rối loạn thần kinh tập thể với sự trơ trẽn trắng trợn đến mức ấy.", "Inversion: Never in + Annals + has + S + V3", [("Never in the annals of modern statecraft", "Cụm trạng ngữ phủ định tuyệt đối về lịch sử chính trị"), ("has a populist demagogue manipulated", "Đảo ngữ với has"), ("collective neuroses with such unabashed cynicism", "Thuật ngữ tâm lý chính trị cao cấp")], "Political Science"),
    ("Not until the archival records were declassified in their entirety did the public comprehend the catastrophic scope of the clandestine operation.", "Mãi cho đến khi các hồ sơ lưu trữ được giải mật toàn bộ, công chúng mới thấu hiểu được quy mô thảm khốc của chiến dịch bí mật đó.", "Not until Clause + did + S + V-bare", [("Not until the archival records were declassified in their entirety", "Mệnh đề thời gian với Not until"), ("did the public comprehend", "Đảo ngữ mệnh đề chính với did"), ("the catastrophic scope of the clandestine operation", "Cụm danh từ học thuật về an ninh tình báo")], "Intelligence History"),
    ("So masterfully did the orator deploy classical zeugma and chiasmus that the assembly was held in rapt, spellbound silence.", "Bậc hùng biện đã triển khai phép ngỗ kết và đối ngẫu cổ điển tài tình đến nỗi cả hội đồng như bị hút hồn trong một sự im lặng mê hoặc.", "Inversion with So + Adverb + did + S + V + that Clause", [("So masterfully did the orator deploy classical zeugma and chiasmus", "Đảo ngữ So masterfully nhấn mạnh kỹ nghệ tu từ học"), ("that the assembly was held in rapt, spellbound silence", "Hệ quả mê hoặc lòng người")], "Classical Rhetoric"),
    ("Scarcely had the constitutional referendum concluded when legal scholars questioned the procedural legitimacy of the electoral apparatus.", "Cuộc trưng cầu dân ý về hiến pháp vừa mới khép lại thì các học giả pháp lý đã đặt nghi vấn về tính hợp pháp trong quy trình của bộ máy bầu cử.", "Scarcely had + S + V3 + when Clause", [("Scarcely had the constitutional referendum concluded", "Đảo ngữ quá khứ hoàn thành với Scarcely"), ("when legal scholars questioned the procedural legitimacy of the electoral apparatus", "Phản biện pháp lý tức thời")], "Constitutional Law"),
    ("Much though the oligarch sought to burnish his public persona through eleemosynary endowments, investigative scrutiny remained unyielding.", "Dẫu cho tên đầu sỏ tài phiệt có tìm cách đánh bóng hình ảnh công chúng bằng các khoản ủy thác từ thiện, sự giám sát điều tra vẫn không hề khoan nhượng.", "Inversion: Much though + S + V, Main Clause", [("Much though the oligarch sought to burnish his public persona through eleemosynary endowments", "Nhượng bộ với Much though kết hợp từ vựng hiếm eleemosynary"), ("investigative scrutiny remained unyielding", "Khẳng định sự bất khuất của báo chí điều tra")], "Investigative Journalism"),
    ("Come what may, the scientific vanguard must safeguard epistemological integrity against ideological encroachment.", "Dù cho chuyện gì có xảy đến đi chăng nữa, đội ngũ tiên phong khoa học vẫn phải bảo vệ tính toàn vẹn của nhận thức luận trước sự xâm lấn của ý thức hệ.", "Subjunctive Idiom: Come what may + S + must + V", [("Come what may", "Thành ngữ giả định cổ điển C2 mang nghĩa dù sóng gió hiểm nguy thế nào"), ("the scientific vanguard must safeguard epistemological integrity", "Nhiệm vụ thiêng liêng của giới tinh hoa khoa học"), ("against ideological encroachment", "Đối tượng xâm hại cần ngăn ngừa")], "Philosophy of Science"),
    ("So entrenched had the bureaucratic inertia become that even existential crises failed to galvanize administrative urgency.", "Sự trì trệ quan liêu đã trở nên ăn sâu bám rễ đến nỗi ngay cả những cuộc khủng hoảng hiện sinh cũng chẳng thể khơi dậy được tính khẩn cấp của bộ máy hành chính.", "Inversion: So + Adjective + had + S + become + that Clause", [("So entrenched had the bureaucratic inertia become", "Đảo ngữ nhấn mạnh sức ì kinh niên của bộ máy"), ("that even existential crises failed to galvanize administrative urgency", "Mệnh đề hệ quả bất lực")], "Public Administration"),
    ("It is with profound circumspection that we must weigh the existential ramifications of autonomous lethal armaments.", "Với sự thận trọng sâu sắc đến tột cùng, chúng ta mới phải cân nhắc những hệ lụy hiện sinh của các loại vũ khí sát thương tự hành.", "Cleft Sentence: It is with + Noun Phrase + that Clause", [("It is with profound circumspection", "Câu chẻ nhấn mạnh mức độ cẩn trọng ngoại giao và đạo đức"), ("that we must weigh the existential ramifications", "Hành động cân nhắc hệ quả sinh tử"), ("of autonomous lethal armaments", "Vũ khí công nghệ cao")], "AI Ethics"),
    ("Hardly had the controversial thesis entered public discourse before it was co-opted and distorted by partisan polemicists.", "Luận điểm gây tranh cãi vừa mới thâm nhập vào diễn ngôn công chúng thì nó đã bị các nhà bút chiến phe phái chiếm đoạt và bóp méo.", "Hardly had + S + V3 + before Clause", [("Hardly had the controversial thesis entered public discourse", "Đảo ngữ với Hardly về diễn ngôn xã hội"), ("before it was co-opted and distorted by partisan polemicists", "Hiện tượng bóp méo học thuyết vì mục đích chính trị")], "Discourse Analysis"),
    ("No matter how convoluted the philosophical dialectic might appear, it ultimately resolves into fundamental ethical imperatives.", "Cho dù biện chứng triết học có vẻ phức tạp và xoắn xuýt đến đâu, rốt cuộc nó vẫn quy về những mệnh lệnh đạo đức nền tảng.", "No matter how + Adjective + S + might + V, Main Clause", [("No matter how convoluted the philosophical dialectic might appear", "Mệnh đề nhượng bộ mức độ phức tạp cao độ"), ("it ultimately resolves into fundamental ethical imperatives", "Kết luận hướng về mệnh lệnh đạo đức học")], "Moral Philosophy"),
    ("Had the geopolitical alliances not been ossified by historical animosities, the maritime dispute could have been resolved through arbitration.", "Nếu như các liên minh địa chính trị không bị xơ cứng bởi những hằn thù lịch sử, cuộc tranh chấp hàng hải lẽ ra đã có thể được giải quyết thông qua trọng tài.", "Inversion of Conditional 3 with Passive Participle", [("Had the geopolitical alliances not been ossified by historical animosities", "Đảo ngữ loại 3 với từ vựng hiếm ossified (hóa đá / xơ cứng)"), ("the maritime dispute could have been resolved through arbitration", "Giải pháp hòa bình bị bỏ lỡ")], "Geopolitics"),
    ("The prose owes its haunting verisimilitude to the author's meticulous excavation of oral histories.", "Ang văn xuôi này có được tính chân thực ám ảnh là nhờ vào sự khai quật tỉ mỉ của tác giả đối với các lịch sử truyền miệng.", "S + owes + Object + to + Noun Phrase", [("The prose owes its haunting verisimilitude", "Cấu trúc owe... to... (có được điều gì là nhờ vào) kết hợp verisimilitude"), ("to the author's meticulous excavation of oral histories", "Nguyên nhân cốt lõi tạo nên kiệt tác")], "Literary Craft"),
    ("Little though the public suspected the systemic fragility of the banking apparatus, catastrophic insolvency loomed on the immediate horizon.", "Dù công chúng chẳng mảy may nghi ngờ về sự mong manh mang tính hệ thống của bộ máy ngân hàng, sự mất khả năng thanh toán thảm khốc vẫn lù lù hiện ra ngay trước mắt.", "Concession with Little though + S + V, Main Clause", [("Little though the public suspected the systemic fragility of the banking apparatus", "Nhượng bộ với Little though nhấn mạnh sự mù mờ của số đông"), ("catastrophic insolvency loomed on the immediate horizon", "Hiểm họa tài chính nhãn tiền cận kề")], "Financial History")
  ]
}

# Format into JS
output_js = "// ============================================================\n"
output_js += "// SENTENCE MASTER DATABASE (CEFR A1 - C2)\n"
output_js += "// Comprehensive full-sentence learning with explicit grammar patterns\n"
output_js += "// ============================================================\n\n"
output_js += "const SENTENCE_DATA = {\n"

cur_id = 1
for lvl in ["A1", "A2", "B1", "B2", "C1", "C2"]:
    output_js += f"  {lvl}: [\n"
    for s_tuple in sentences_by_level[lvl]:
        sent, meaning, pattern, breakdown_raw, topic = s_tuple
        # Split words cleanly into chips
        words = sent.split()
        breakdown_objs = [{"part": b[0], "role": b[1]} for b in breakdown_raw]
        
        sent_obj = {
            "id": cur_id,
            "level": lvl,
            "sentence": sent,
            "meaning": meaning,
            "pattern": pattern,
            "breakdown": breakdown_objs,
            "words": words,
            "topic": topic
        }
        output_js += "    " + json.dumps(sent_obj, ensure_ascii=False) + ",\n"
        cur_id += 1
    output_js += "  ],\n"

output_js += "};\n"

with open("data/sentences.js", "w", encoding="utf-8") as f:
    f.write(output_js)

print(f"Generated data/sentences.js with {cur_id - 1} total sentences across A1-C2!")
