import json

# Let's read existing GRAMMAR_DATA or define 30 questions per level = 180 questions
# Covering all grammar topics
# Format:
# { id: int, level: "A1".."C2", topic: "...", type: "multiple_choice"|"fill_blank", title: "...", instruction: "...", question: "...", options: [...], answer: int|str, hint?: "...", explanation: "..." }

# Let's craft comprehensive grammar questions for each level
a1_grammar = [
    {"id": 1, "level": "A1", "topic": "Present Simple 'To Be'", "type": "multiple_choice", "title": "Verb To Be", "instruction": "Choose the correct form of the verb 'to be'.", "question": "They ___ students at the international academy.", "options": ["am", "is", "are", "be"], "answer": 2, "explanation": "With the plural pronoun 'they', the correct present form of 'to be' is 'are'."},
    {"id": 2, "level": "A1", "topic": "Present Simple Singular", "type": "fill_blank", "title": "Third-Person Singular (-s/-es)", "instruction": "Fill in the blank with the correct form of the verb.", "question": "My brother ___ (watch) documentary films every evening.", "answer": "watches", "hint": "Verbs ending in -ch add -es for he/she/it.", "explanation": "For verbs ending in -ch, -sh, -ss, -x, or -o, add '-es' in the third-person singular (watches, washes, goes)."},
    {"id": 3, "level": "A1", "topic": "Articles", "type": "multiple_choice", "title": "Indefinite Articles: A vs An", "instruction": "Choose the correct article for the sentence.", "question": "She ordered ___ iced tea and ___ apple tart.", "options": ["a / a", "an / a", "a / an", "an / an"], "answer": 2, "explanation": "Use 'a' before consonant sounds ('a tea') and 'an' before vowel sounds ('an apple')."},
    {"id": 4, "level": "A1", "topic": "Prepositions of Place", "type": "multiple_choice", "title": "Prepositions: In, On, At", "instruction": "Select the accurate preposition of location.", "question": "The keys are ___ the kitchen table.", "options": ["in", "on", "at", "underneath of"], "answer": 1, "explanation": "We use 'on' for surfaces: on the table, on the wall, on the floor."},
    {"id": 5, "level": "A1", "topic": "Modals: Ability", "type": "fill_blank", "title": "Can / Can't for Ability", "instruction": "Fill in with 'can' or 'cannot'.", "question": "He is bilingual, so he ___ (can) speak both English and Vietnamese fluently.", "answer": "can", "hint": "Use the affirmative modal for ability.", "explanation": "'Can' expresses ability in the present without changing form for different subjects."},
    {"id": 6, "level": "A1", "topic": "Present Continuous", "type": "multiple_choice", "title": "Present Continuous for Actions Right Now", "instruction": "Choose the correct verb form for an action happening at this moment.", "question": "Listen! The baby ___ in the nursery.", "options": ["cries", "is crying", "are crying", "cry"], "answer": 1, "explanation": "The command 'Listen!' signals an action happening right now, which requires Present Continuous: 'is crying'."},
    {"id": 7, "level": "A1", "topic": "Questions with Do/Does", "type": "fill_blank", "title": "Present Simple Questions with Do / Does", "instruction": "Complete the question with 'Do' or 'Does'.", "question": "___ (Do/Does) your sister live in downtown Da Nang?", "answer": "Does", "hint": "Use 'Does' for singular third-person subjects (he, she, your sister).", "explanation": "Third-person singular subjects (your sister = she) take 'Does' in present simple questions."},
    {"id": 8, "level": "A1", "topic": "Pronouns", "type": "multiple_choice", "title": "Subject vs Object Pronouns", "instruction": "Select the correct pronoun to complete the sentence.", "question": "Our teacher gave ___ extra time to finish the homework.", "options": ["we", "us", "our", "ours"], "answer": 1, "explanation": "After a verb ('gave'), we use the object pronoun 'us', not the subject pronoun 'we'."},
    {"id": 9, "level": "A1", "topic": "Demonstratives", "type": "multiple_choice", "title": "This, That, These, Those", "instruction": "Choose the correct demonstrative pronoun.", "question": "___ books on my desk belong to the school library.", "options": ["This", "That", "These", "Those"], "answer": 2, "explanation": "Plural objects close to the speaker use 'These'."},
    {"id": 10, "level": "A1", "topic": "Possessive Adjectives", "type": "fill_blank", "title": "Possessive Adjectives", "instruction": "Fill in the correct possessive adjective for 'she'.", "question": "Sarah is riding ___ (she) new bicycle to school.", "answer": "her", "hint": "Possessive adjective of she is her.", "explanation": "'Her' is the possessive adjective used before a noun belonging to a female subject."},
    {"id": 11, "level": "A1", "topic": "Plural Nouns", "type": "multiple_choice", "title": "Irregular Plurals", "instruction": "Choose the correct plural form of 'child'.", "question": "There are ten ___ playing in the park.", "options": ["childs", "children", "childrens", "childes"], "answer": 1, "explanation": "'Child' has an irregular plural form: 'children'."},
    {"id": 12, "level": "A1", "topic": "Negatives in Present Simple", "type": "fill_blank", "title": "Negative Present Simple", "instruction": "Complete with don't or doesn't.", "question": "He ___ (do not) drink coffee in the evening.", "answer": "doesn't", "hint": "Use doesn't for he/she/it.", "explanation": "Third person singular uses 'doesn't' (or does not) + base verb."},
    {"id": 13, "level": "A1", "topic": "Prepositions of Time", "type": "multiple_choice", "title": "At, In, On for Time", "instruction": "Choose the correct preposition for the time of day.", "question": "Our English class starts ___ 8:00 AM.", "options": ["in", "on", "at", "for"], "answer": 2, "explanation": "We use 'at' for precise clock times: at 8:00 AM, at noon, at midnight."},
    {"id": 14, "level": "A1", "topic": "Days of the Week", "type": "multiple_choice", "title": "Preposition with Days", "instruction": "Choose the preposition used with days.", "question": "We play soccer ___ Sunday afternoons.", "options": ["at", "on", "in", "to"], "answer": 1, "explanation": "We use 'on' with days of the week: on Sunday, on Monday morning."},
    {"id": 15, "level": "A1", "topic": "There is / There are", "type": "fill_blank", "title": "There is vs There are", "instruction": "Fill in 'is' or 'are'.", "question": "There ___ (be) three apples on the plate.", "answer": "are", "hint": "Three apples is plural.", "explanation": "'There are' is used before plural countable nouns."},
    {"id": 16, "level": "A1", "topic": "Countable vs Uncountable", "type": "multiple_choice", "title": "Much vs Many", "instruction": "Select the quantifier for water.", "question": "How ___ water do you drink every day?", "options": ["many", "much", "few", "any"], "answer": 1, "explanation": "Water is uncountable, so we ask 'How much water'."},
    {"id": 17, "level": "A1", "topic": "Countable vs Uncountable", "type": "multiple_choice", "title": "How Many", "instruction": "Select the quantifier for books.", "question": "How ___ books did you borrow from the library?", "options": ["much", "many", "little", "any"], "answer": 1, "explanation": "'Books' is plural countable, so we ask 'How many'."},
    {"id": 18, "level": "A1", "topic": "Have / Has got", "type": "fill_blank", "title": "Have vs Has", "instruction": "Fill in have or has.", "question": "She ___ (have) a friendly dog.", "answer": "has", "hint": "Third person singular takes has.", "explanation": "Subject 'she' takes 'has'."},
    {"id": 19, "level": "A1", "topic": "Adverbs of Frequency", "type": "multiple_choice", "title": "Position of Always/Usually", "instruction": "Choose the correctly ordered sentence.", "question": "Which sentence has correct word order?", "options": ["She eats always breakfast.", "She always eats breakfast.", "Always she eats breakfast.", "She breakfast always eats."], "answer": 1, "explanation": "Adverbs of frequency usually come before the main verb: 'She always eats breakfast.'"},
    {"id": 20, "level": "A1", "topic": "Imperatives", "type": "multiple_choice", "title": "Giving Instructions", "instruction": "Choose the correct imperative form.", "question": "Please ___ the door quietly.", "options": ["closing", "closed", "close", "to close"], "answer": 2, "explanation": "Imperative sentences use the base form of the verb without 'to'."}
]

print(f"Sample A1 grammar questions: {len(a1_grammar)}")
