import json
import os

# Define 100 words per level for CEFR A1, A2, B1, B2, C1, C2 (600 words total)
a1_words = [
    (1, "hello", "/həˈloʊ/", "exclamation", "xin chào", "Hello, how are you today?", "greetings"),
    (2, "goodbye", "/ɡʊdˈbaɪ/", "exclamation", "tạm biệt", "Goodbye, see you tomorrow morning!", "greetings"),
    (3, "thank you", "/θæŋk juː/", "phrase", "cảm ơn bạn", "Thank you very much for your kind help.", "politeness"),
    (4, "please", "/pliːz/", "adverb", "làm ơn, xin vui lòng", "Please pass me the water bottle.", "politeness"),
    (5, "water", "/ˈwɔːtər/", "noun", "nước uống", "I drink eight glasses of fresh water daily.", "food & drink"),
    (6, "food", "/fuːd/", "noun", "thức ăn, thực phẩm", "Vietnamese street food is famous and delicious.", "food & drink"),
    (7, "bread", "/bred/", "noun", "bánh mì", "He eats toasted bread with butter every breakfast.", "food & drink"),
    (8, "milk", "/mɪlk/", "noun", "sữa", "Children drink warm milk before going to sleep.", "food & drink"),
    (9, "tea", "/tiː/", "noun", "trà, chè", "My grandfather enjoys a cup of hot green tea.", "food & drink"),
    (10, "coffee", "/ˈkɔːfi/", "noun", "cà phê", "She drinks iced coffee to stay awake in the morning.", "food & drink"),
    (11, "apple", "/ˈæpl/", "noun", "quả táo", "An apple a day keeps the doctor away.", "food & drink"),
    (12, "book", "/bʊk/", "noun", "quyển sách", "She reads an inspiring English book every night.", "objects"),
    (13, "pen", "/pen/", "noun", "bút mực", "Can I borrow your blue pen to write my name?", "objects"),
    (14, "notebook", "/ˈnoʊtbʊk/", "noun", "vở ghi chép", "I write new vocabulary in this small notebook.", "objects"),
    (15, "bag", "/bæɡ/", "noun", "cặp sách, túi xách", "He puts his heavy textbooks inside his school bag.", "objects"),
    (16, "friend", "/frend/", "noun", "người bạn", "A true friend is always there to support you.", "people"),
    (17, "family", "/ˈfæməli/", "noun", "gia đình", "My family gathers together for dinner every Sunday.", "family"),
    (18, "mother", "/ˈmʌðər/", "noun", "mẹ", "My mother cooks the most delicious meals at home.", "family"),
    (19, "father", "/ˈfɑːðər/", "noun", "bố, cha", "His father teaches him how to ride a bicycle.", "family"),
    (20, "sister", "/ˈsɪstər/", "noun", "chị, em gái", "My younger sister loves singing English songs.", "family"),
    (21, "brother", "/ˈbrʌðər/", "noun", "anh, em trai", "His elder brother plays football in the school team.", "family"),
    (22, "house", "/haʊs/", "noun", "ngôi nhà", "They live in a beautiful house with a green garden.", "home"),
    (23, "room", "/ruːm/", "noun", "căn phòng", "My bedroom is quiet and comfortable for studying.", "home"),
    (24, "door", "/dɔːr/", "noun", "cánh cửa", "Please close the front door when you leave.", "home"),
    (25, "window", "/ˈwɪndoʊ/", "noun", "cửa sổ", "Open the window to let fresh air into the room.", "home"),
    (26, "table", "/ˈteɪbl/", "noun", "cái bàn", "There is a wooden table in the center of the kitchen.", "home"),
    (27, "chair", "/tʃer/", "noun", "cái ghế", "Please take a chair and sit down.", "home"),
    (28, "bed", "/bed/", "noun", "cái giường", "I go to bed early so I can wake up refreshed.", "home"),
    (29, "clock", "/klɑːk/", "noun", "đồng hồ treo tường", "The wall clock shows that it is exactly seven o'clock.", "home"),
    (30, "phone", "/foʊn/", "noun", "điện thoại", "She uses her smart phone to practice pronunciation.", "technology"),
    (31, "happy", "/ˈhæpi/", "adjective", "vui vẻ, hạnh phúc", "The children are very happy on their birthday.", "feelings"),
    (32, "sad", "/sæd/", "adjective", "buồn bã", "He felt sad when his favorite football team lost.", "feelings"),
    (33, "tired", "/ˈtaɪərd/", "adjective", "mệt mỏi", "I am tired after working hard at school all day.", "feelings"),
    (34, "hungry", "/ˈhʌŋɡri/", "adjective", "đói bụng", "Let's find a restaurant because I am very hungry.", "feelings"),
    (35, "thirsty", "/ˈθɜːrsti/", "adjective", "khát nước", "After running five miles, he was extremely thirsty.", "feelings"),
    (36, "hot", "/hɑːt/", "adjective", "nóng bức", "The summer weather in Hanoi is often very hot.", "weather"),
    (37, "cold", "/koʊld/", "adjective", "lạnh giá", "Drink hot ginger tea when the weather gets cold.", "weather"),
    (38, "big", "/bɪɡ/", "adjective", "to lớn", "They moved into a big apartment in the city center.", "descriptions"),
    (39, "small", "/smɔːl/", "adjective", "nhỏ nhắn", "She carries a small umbrella in her handbag.", "descriptions"),
    (40, "new", "/nuː/", "adjective", "mới", "I bought a new English dictionary yesterday.", "descriptions"),
    (41, "old", "/oʊld/", "adjective", "cũ, già", "This old library has thousands of historic books.", "descriptions"),
    (42, "good", "/ɡʊd/", "adjective", "tốt, giỏi", "She is a very good English speaker.", "descriptions"),
    (43, "bad", "/bæd/", "adjective", "xấu, tồi", "Eating too much sugar is bad for your teeth.", "descriptions"),
    (44, "easy", "/ˈiːzi/", "adjective", "dễ dàng", "Practice every day to make English learning easy.", "descriptions"),
    (45, "difficult", "/ˈdɪfɪkəlt/", "adjective", "khó khăn", "Pronouncing some sounds can be difficult at first.", "descriptions"),
    (46, "beautiful", "/ˈbjuːtɪfl/", "adjective", "xinh đẹp", "The sunset over the West Lake is breathtakingly beautiful.", "descriptions"),
    (47, "eat", "/iːt/", "verb", "ăn", "We usually eat dinner together at seven in the evening.", "actions"),
    (48, "drink", "/drɪŋk/", "verb", "uống", "Remember to drink enough water throughout the day.", "actions"),
    (49, "sleep", "/sliːp/", "verb", "ngủ", "Babies need to sleep ten to twelve hours every day.", "actions"),
    (50, "wake up", "/weɪk ʌp/", "verb", "thức dậy", "I wake up at six every morning to exercise.", "daily routines"),
    (51, "walk", "/wɔːk/", "verb", "đi bộ", "They walk in the public park every afternoon.", "actions"),
    (52, "run", "/rʌn/", "verb", "chạy", "He likes to run around the lake on weekends.", "actions"),
    (53, "read", "/riːd/", "verb", "đọc", "Students read short stories to build vocabulary.", "actions"),
    (54, "write", "/raɪt/", "verb", "viết", "Write five English sentences in your journal daily.", "actions"),
    (55, "speak", "/spiːk/", "verb", "nói", "Don't be afraid to speak English with confidence.", "actions"),
    (56, "listen", "/ˈlɪsn/", "verb", "lắng nghe", "Listen carefully to native podcast speakers.", "actions"),
    (57, "learn", "/lɜːrn/", "verb", "học tập", "Learning a new language opens up world opportunities.", "education"),
    (58, "understand", "/ˌʌndərˈstænd/", "verb", "hiểu được", "Do you understand what the teacher explained?", "communication"),
    (59, "help", "/help/", "verb", "giúp đỡ", "She helps her younger brother with English homework.", "actions"),
    (60, "buy", "/baɪ/", "verb", "mua sắm", "I need to buy some fresh vegetables at the market.", "shopping"),
    (61, "sell", "/sel/", "verb", "bán", "They sell tropical fruit and fresh flowers here.", "shopping"),
    (62, "open", "/ˈoʊpən/", "verb", "mở ra", "Open your books to page twenty-five, please.", "actions"),
    (63, "close", "/kloʊz/", "verb", "đóng lại", "Please close the window before it starts raining.", "actions"),
    (64, "like", "/laɪk/", "verb", "thích", "I really like learning foreign languages and cultures.", "feelings"),
    (65, "love", "/lʌv/", "verb", "yêu thương", "Parents love their children with all their hearts.", "feelings"),
    (66, "live", "/lɪv/", "verb", "sống, cư ngụ", "They live in a peaceful neighborhood near the river.", "home"),
    (67, "work", "/wɜːrk/", "verb", "làm việc", "My parents work at a busy international hospital.", "work"),
    (68, "study", "/ˈstʌdi/", "verb", "học tập, nghiên cứu", "He studies English grammar two hours each night.", "education"),
    (69, "play", "/pleɪ/", "verb", "chơi đùa", "Children love to play outside in the playground.", "actions"),
    (70, "stop", "/stɑːp/", "verb", "dừng lại", "Drivers must stop when the traffic light turns red.", "transport"),
    (71, "start", "/stɑːrt/", "verb", "bắt đầu", "The English lesson will start in five minutes.", "actions"),
    (72, "finish", "/ˈfɪnɪʃ/", "verb", "kết thúc, hoàn thành", "She hopes to finish her homework before nine PM.", "actions"),
    (73, "go", "/ɡoʊ/", "verb", "đi", "Let's go to the city library to study together.", "actions"),
    (74, "come", "/kʌm/", "verb", "đến, tới", "Please come inside out of the cold weather.", "actions"),
    (75, "see", "/siː/", "verb", "nhìn thấy", "Can you see the tall mountain in the distance?", "senses"),
    (76, "hear", "/hɪr/", "verb", "nghe thấy", "I can hear sweet birds singing outside the window.", "senses"),
    (77, "today", "/təˈdeɪ/", "noun", "hôm nay", "Today is a wonderful day to learn something new.", "time"),
    (78, "tomorrow", "/təˈmɔːroʊ/", "noun", "ngày mai", "We have an important vocabulary test tomorrow morning.", "time"),
    (79, "yesterday", "/ˈjestərdeɪ/", "noun", "hôm qua", "Yesterday was Sunday, so I rested at home.", "time"),
    (80, "morning", "/ˈmɔːrnɪŋ/", "noun", "buổi sáng", "I enjoy drinking hot coffee every sunny morning.", "time"),
    (81, "afternoon", "/ˌæftərˈnuːn/", "noun", "buổi chiều", "They practice conversation every Monday afternoon.", "time"),
    (82, "evening", "/ˈiːvnɪŋ/", "noun", "buổi tối", "We watch educational documentaries in the evening.", "time"),
    (83, "night", "/naɪt/", "noun", "ban đêm", "The starry night sky looks incredibly clear tonight.", "time"),
    (84, "time", "/taɪm/", "noun", "thời gian", "What time does your English class begin?", "time"),
    (85, "day", "/deɪ/", "noun", "ngày", "There are seven days in a normal week.", "time"),
    (86, "week", "/wiːk/", "noun", "tuần lễ", "She studies twenty new vocabulary words each week.", "time"),
    (87, "month", "/mʌnθ/", "noun", "tháng", "December is usually the coldest month of the year.", "time"),
    (88, "year", "/jɪr/", "noun", "năm", "He plans to travel to London next year.", "time"),
    (89, "sun", "/sʌn/", "noun", "mặt trời", "The morning sun rises brightly from the east.", "nature"),
    (90, "moon", "/muːn/", "noun", "mặt trăng", "The full moon shines brightly in the autumn sky.", "nature"),
    (91, "star", "/stɑːr/", "noun", "ngôi sao", "Look up at the countless stars shining tonight.", "nature"),
    (92, "sky", "/skaɪ/", "noun", "bầu trời", "The blue sky has white fluffy clouds drifting by.", "nature"),
    (93, "tree", "/triː/", "noun", "cây cối", "Birds build their cozy nests high in the big green tree.", "nature"),
    (94, "flower", "/ˈflaʊər/", "noun", "bông hoa", "She received a bouquet of red flowers on her birthday.", "nature"),
    (95, "cat", "/kæt/", "noun", "con mèo", "The playful cat is sleeping on the warm sofa.", "animals"),
    (96, "dog", "/dɔːɡ/", "noun", "con chó", "Our loyal dog wags his tail whenever we return home.", "animals"),
    (97, "school", "/skuːl/", "noun", "trường học", "Students ride their bikes to school every weekday.", "places"),
    (98, "teacher", "/ˈtiːtʃər/", "noun", "giáo viên", "Our English teacher explains grammar very clearly.", "people"),
    (99, "student", "/ˈstuːdnt/", "noun", "học sinh, sinh viên", "The diligent student always finishes his homework.", "people"),
    (100, "city", "/ˈsɪti/", "noun", "thành phố", "Ho Chi Minh City is a bustling and lively city.", "places")
]

a2_words = [
    (101, "travel", "/ˈtrævl/", "verb", "du lịch, đi lại", "They plan to travel abroad during the summer vacation.", "travel"),
    (102, "airport", "/ˈerpɔːrt/", "noun", "sân bay", "We arrived at the international airport two hours early.", "transport"),
    (103, "passport", "/ˈpæspɔːrt/", "noun", "hộ chiếu", "Keep your passport and boarding pass in a secure pocket.", "travel"),
    (104, "ticket", "/ˈtɪkɪt/", "noun", "vé xe, vé máy bay", "I booked a train ticket to Da Nang online.", "travel"),
    (105, "luggage", "/ˈlʌɡɪdʒ/", "noun", "hành lý", "Make sure your luggage weighs under twenty kilograms.", "travel"),
    (106, "hotel", "/hoʊˈtel/", "noun", "khách sạn", "We reserved a cozy hotel room overlooking the beach.", "places"),
    (107, "restaurant", "/ˈrestrɑːnt/", "noun", "nhà hàng", "This traditional restaurant serves authentic local food.", "places"),
    (108, "market", "/ˈmɑːrkɪt/", "noun", "chợ, thị trường", "My mother buys fresh produce at the morning market.", "places"),
    (109, "hospital", "/ˈhɑːspɪtl/", "noun", "bệnh viện", "The new hospital is equipped with modern medical devices.", "places"),
    (110, "station", "/ˈsteɪʃn/", "noun", "nhà ga, trạm xe", "Meet me at the central metro station at noon.", "transport"),
    (111, "bus", "/bʌs/", "noun", "xe buýt", "Riding the electric bus is clean and economical.", "transport"),
    (112, "train", "/treɪn/", "noun", "tàu hỏa", "The high-speed train travels from north to south smoothly.", "transport"),
    (113, "bicycle", "/ˈbaɪsɪkl/", "noun", "xe đạp", "Riding a bicycle every morning keeps you physically fit.", "transport"),
    (114, "driver", "/ˈdraɪvər/", "noun", "tài xế", "The taxi driver knew all the shortest shortcuts in the city.", "people"),
    (115, "direction", "/dəˈrekʃn/", "noun", "phương hướng, chỉ dẫn", "Excuse me, could you give me directions to the museum?", "travel"),
    (116, "weather", "/ˈweðər/", "noun", "thời tiết", "Check the weather forecast before packing for your trip.", "weather"),
    (117, "rain", "/reɪn/", "noun", "mưa", "Take an umbrella because heavy rain is expected today.", "weather"),
    (118, "cloudy", "/ˈklaʊdi/", "adjective", "nhiều mây, u ám", "It was a cloudy morning, but the sun came out by noon.", "weather"),
    (119, "windy", "/ˈwɪndi/", "adjective", "lộng gió, nhiều gió", "It was so windy that my hat blew away on the beach.", "weather"),
    (120, "sunny", "/ˈsʌni/", "adjective", "nắng ráo", "We enjoyed a warm sunny day at the seaside.", "weather"),
    (121, "clothes", "/kloʊðz/", "noun", "quần áo, trang phục", "Pack comfortable casual clothes for the hiking trip.", "shopping"),
    (122, "shirt", "/ʃɜːrt/", "noun", "áo sơ mi", "He wears a formal white shirt for job interviews.", "clothing"),
    (123, "shoes", "/ʃuːz/", "noun", "đôi giày", "These running shoes provide great arch support.", "clothing"),
    (124, "jacket", "/ˈdʒækɪt/", "noun", "áo khoác", "Wear a warm winter jacket when walking in the snow.", "clothing"),
    (125, "price", "/praɪs/", "noun", "giá cả", "The price of organic vegetables has dropped this week.", "shopping"),
    (126, "cheap", "/tʃiːp/", "adjective", "rẻ, giá thấp", "Street markets offer delicious food at very cheap prices.", "shopping"),
    (127, "expensive", "/ɪkˈspensɪv/", "adjective", "đắt đỏ", "Luxury imported watches are often quite expensive.", "shopping"),
    (128, "discount", "/ˈdɪskaʊnt/", "noun", "khoản giảm giá", "Students get a ten percent discount at this bookstore.", "shopping"),
    (129, "doctor", "/ˈdɑːktər/", "noun", "bác sĩ", "You should consult a doctor if your cough continues.", "health"),
    (130, "medicine", "/ˈmedɪsn/", "noun", "thuốc trị bệnh", "Take this prescribed medicine twice daily after meals.", "health"),
    (131, "headache", "/ˈhedeɪk/", "noun", "chứng đau đầu", "Drinking plenty of water often relieves a mild headache.", "health"),
    (132, "healthy", "/ˈhelθi/", "adjective", "khỏe mạnh, lành mạnh", "A balanced diet and daily exercise promote a healthy lifestyle.", "health"),
    (133, "exercise", "/ˈeksərsaɪz/", "verb", "tập thể dục, rèn luyện", "It is beneficial to exercise at least thirty minutes a day.", "health"),
    (134, "hobby", "/ˈhɑːbi/", "noun", "sở thích", "Photography is her favorite creative weekend hobby.", "lifestyle"),
    (135, "music", "/ˈmjuːzɪk/", "noun", "âm nhạc", "Listening to classical music helps me focus while studying.", "arts"),
    (136, "movie", "/ˈmuːvi/", "noun", "bộ phim", "We watched an exciting action movie at the cinema.", "entertainment"),
    (137, "sport", "/spɔːrt/", "noun", "thể thao", "Swimming is a popular summer sport among youth.", "sports"),
    (138, "holiday", "/ˈhɑːlədeɪ/", "noun", "kỳ nghỉ, ngày lễ", "Tet is the most important national holiday in Vietnam.", "culture"),
    (139, "birthday", "/ˈbɜːrθdeɪ/", "noun", "ngày sinh nhật", "Her friends organized a surprise birthday party for her.", "celebration"),
    (140, "gift", "/ɡɪft/", "noun", "món quà tặng", "A handwritten card is a thoughtful birthday gift.", "celebration"),
    (141, "computer", "/kəmˈpjuːtər/", "noun", "máy tính", "Modern computers can process vast amounts of information.", "technology"),
    (142, "internet", "/ˈɪntərnet/", "noun", "mạng internet", "The internet enables people to study English from anywhere.", "technology"),
    (143, "email", "/ˈiːmeɪl/", "noun", "thư điện tử", "I sent an email confirming the appointment yesterday.", "communication"),
    (144, "message", "/ˈmesɪdʒ/", "noun", "tin nhắn", "Leave a voice message if no one answers the phone.", "communication"),
    (145, "website", "/ˈwebsaɪt/", "noun", "trang web", "This interactive website offers great pronunciation practice.", "technology"),
    (146, "password", "/ˈpæswɜːrd/", "noun", "mật khẩu bảo vệ", "Always choose a strong password with letters and numbers.", "technology"),
    (147, "kitchen", "/ˈkɪtʃɪn/", "noun", "phòng bếp", "They remodeled their kitchen with modern appliances.", "home"),
    (148, "cook", "/kʊk/", "verb", "nấu ăn", "Learning to cook fresh meals saves money and boosts health.", "actions"),
    (149, "clean", "/kliːn/", "adjective", "sạch sẽ", "Keep your study desk neat and clean to improve focus.", "descriptions"),
    (150, "dirty", "/ˈdɜːrti/", "adjective", "bẩn thỉu", "Put your dirty clothes straight into the laundry basket.", "descriptions"),
    (151, "wash", "/wɑːʃ/", "verb", "giặt giũ, rửa sạch", "Always wash your hands thoroughly before eating meals.", "health"),
    (152, "shower", "/ˈʃaʊər/", "noun", "vòi sen, tắm vòi sen", "A warm morning shower helps wake up your body.", "daily routines"),
    (153, "brush", "/brʌʃ/", "verb", "chải, đánh (răng)", "Dentists advise that you brush your teeth twice daily.", "health"),
    (154, "wear", "/wer/", "verb", "mặc, đeo", "Students wear clean uniforms when attending school.", "actions"),
    (155, "choose", "/tʃuːz/", "verb", "lựa chọn", "Take your time to choose the best option from the list.", "actions"),
    (156, "decide", "/dɪˈsaɪd/", "verb", "quyết định", "She must decide whether to study business or art.", "actions"),
    (157, "remember", "/rɪˈmembər/", "verb", "ghi nhớ", "Flashcards help learners remember new vocabulary effectively.", "memory"),
    (158, "forget", "/fərˈɡet/", "verb", "quên mất", "Write down your appointments so you don't forget them.", "memory"),
    (159, "bring", "/brɪŋ/", "verb", "mang theo, đem đến", "Don't forget to bring your English textbook tomorrow.", "actions"),
    (160, "send", "/send/", "verb", "gửi đi", "I will send you the document as a PDF attachment.", "communication"),
    (161, "receive", "/rɪˈsiːv/", "verb", "nhận được", "Did you receive the confirmation email from the school?", "communication"),
    (162, "explain", "/ɪkˈspleɪn/", "verb", "giải thích", "Could you explain the difference between these two words?", "communication"),
    (163, "practice", "/ˈpræktɪs/", "verb", "luyện tập", "Practice speaking aloud every single day to gain fluency.", "education"),
    (164, "improve", "/ɪmˈpruːv/", "verb", "cải thiện, tiến bộ", "Her English listening skills continue to improve rapidly.", "education"),
    (165, "mistake", "/mɪˈsteɪk/", "noun", "lỗi sai, sai sót", "Making mistakes is a normal and necessary part of learning.", "education"),
    (166, "correct", "/kəˈrekt/", "adjective", "chính xác, đúng đắn", "Check your answers to ensure all grammar is correct.", "education"),
    (167, "answer", "/ˈænsər/", "noun", "câu trả lời", "Raise your hand if you know the correct answer.", "education"),
    (168, "question", "/ˈkwestʃən/", "noun", "câu hỏi", "Feel free to ask any question during the study session.", "education"),
    (169, "problem", "/ˈprɑːbləm/", "noun", "vấn đề, khó khăn", "We can solve this technical problem by working together.", "challenges"),
    (170, "solution", "/səˈluːʃn/", "noun", "giải pháp", "Finding a creative solution requires critical thinking.", "challenges"),
    (171, "simple", "/ˈsɪmpl/", "adjective", "đơn giản, mộc mạc", "Use simple sentences until you feel confident speaking.", "descriptions"),
    (172, "clever", "/ˈklevər/", "adjective", "thông minh, khéo léo", "The clever boy found a quick way to solve the puzzle.", "personality"),
    (173, "polite", "/pəˈlaɪt/", "adjective", "lịch sự, nhã nhặn", "It is polite to say 'please' and 'thank you' in English.", "personality"),
    (174, "friendly", "/ˈfrendli/", "adjective", "thân thiện, cởi mở", "The local villagers were remarkably warm and friendly.", "personality"),
    (175, "quiet", "/ˈkwaɪət/", "adjective", "yên tĩnh, trầm lặng", "The public library is a quiet place for reading books.", "descriptions"),
    (176, "noisy", "/ˈnɔɪzi/", "adjective", "ồn ào, náo nhiệt", "The street market was noisy with bargaining voices.", "descriptions"),
    (177, "crowded", "/ˈkraʊdɪd/", "adjective", "đông đúc, chật ních", "The subway trains get crowded during morning rush hour.", "places"),
    (178, "famous", "/ˈfeɪməs/", "adjective", "nổi tiếng", "Ha Long Bay is famous worldwide for its limestone islands.", "descriptions"),
    (179, "modern", "/ˈmɑːdərn/", "adjective", "hiện đại, tân tiến", "The university boasts modern laboratories and dorms.", "descriptions"),
    (180, "traditional", "/trəˈdɪʃənl/", "adjective", "truyền thống", "Ao Dai is the graceful traditional garment of Vietnam.", "culture"),
    (181, "hobby", "/ˈhɑːbi/", "noun", "thú vui, sở thích", "Gardening is a relaxing hobby for many retired people.", "lifestyle"),
    (182, "garden", "/ˈɡɑːrdn/", "noun", "khu vườn", "They grow organic herbs and tomatoes in their backyard garden.", "nature"),
    (183, "river", "/ˈrɪvər/", "noun", "dòng sông", "Boats glide along the calm river at dusk.", "nature"),
    (184, "mountain", "/ˈmaʊntn/", "noun", "ngọn núi", "Hikers climbed to the peak of the mountain at sunrise.", "nature"),
    (185, "beach", "/biːtʃ/", "noun", "bãi biển", "Families enjoy walking along the sandy beach on weekends.", "nature"),
    (186, "island", "/ˈaɪlənd/", "noun", "hòn đảo", "Phu Quoc is a scenic tropical island in southern Vietnam.", "places"),
    (187, "forest", "/ˈfɔːrɪst/", "noun", "khu rừng", "The ancient forest is home to diverse species of wildlife.", "nature"),
    (188, "animal", "/ˈænɪml/", "noun", "động vật", "We should protect endangered wild animals and their habitats.", "animals"),
    (189, "bird", "/bɜːrd/", "noun", "loài chim", "Migratory birds fly south to escape harsh winter frost.", "animals"),
    (190, "fish", "/fɪʃ/", "noun", "loài cá", "Freshwater fish swim in schools beneath the clear stream.", "animals"),
    (191, "traffic", "/ˈtræfɪk/", "noun", "giao thông", "City traffic gets congested during peak evening hours.", "transport"),
    (192, "street", "/striːt/", "noun", "đường phố", "Tree-lined streets make walking pleasant in autumn.", "places"),
    (193, "building", "/ˈbɪldɪŋ/", "noun", "tòa nhà", "The tallest building in the city offers a panoramic view.", "places"),
    (194, "bridge", "/brɪdʒ/", "noun", "cây cầu", "The historic suspension bridge links the two districts.", "places"),
    (195, "culture", "/ˈkʌltʃər/", "noun", "nền văn hóa", "Traveling teaches you to respect diverse world cultures.", "culture"),
    (196, "language", "/ˈlæŋɡwɪdʒ/", "noun", "ngôn ngữ", "Learning a foreign language builds bridge across nations.", "education"),
    (197, "grammar", "/ˈɡræmər/", "noun", "ngữ pháp", "Clear grammar helps you convey your exact thoughts.", "education"),
    (198, "sentence", "/ˈsentəns/", "noun", "câu văn", "Forming a complete English sentence requires a subject and verb.", "education"),
    (199, "meaning", "/ˈmiːnɪŋ/", "noun", "ý nghĩa, định nghĩa", "Look up the contextual meaning of words you encounter.", "education"),
    (200, "dialogue", "/ˈdaɪəlɔːɡ/", "noun", "cuộc hội thoại", "Practice reading this everyday dialogue with a study partner.", "communication")
]

b1_words = [
    (201, "opportunity", "/ˌɑːpərˈtuːnəti/", "noun", "cơ hội, thời cơ", "Studying English creates countless career opportunities.", "career"),
    (202, "experience", "/ɪkˈspɪriəns/", "noun", "kinh nghiệm, trải nghiệm", "Hands-on experience is invaluable for career advancement.", "career"),
    (203, "colleague", "/ˈkɑːliːɡ/", "noun", "đồng nghiệp", "He collaborates closely with international colleagues.", "workplace"),
    (204, "manager", "/ˈmænɪdʒər/", "noun", "người quản lý", "The project manager assigned specific deliverables to each team member.", "workplace"),
    (205, "interview", "/ˈɪntərvjuː/", "noun", "buổi phỏng vấn", "Prepare answers to standard questions before your job interview.", "career"),
    (206, "resume", "/ˈrezəmeɪ/", "noun", "sơ yếu lý lịch (CV)", "Tailor your resume to highlight relevant achievements.", "career"),
    (207, "salary", "/ˈsæləri/", "noun", "tiền lương", "The company offers a competitive starting salary and benefits.", "finance"),
    (208, "budget", "/ˈbʌdʒɪt/", "noun", "ngân sách chi tiêu", "Stick to a monthly budget to save for your future goals.", "finance"),
    (209, "investment", "/ɪnˈvestmənt/", "noun", "khoản đầu tư", "Education is the best long-term investment you can make.", "finance"),
    (210, "environment", "/ɪnˈvaɪrənmənt/", "noun", "môi trường tự nhiên", "Renewable energy helps preserve our fragile environment.", "environment"),
    (211, "pollution", "/pəˈluːʃn/", "noun", "sự ô nhiễm", "Air pollution in major metropolises poses public health risks.", "environment"),
    (212, "recycle", "/ˌriːˈsaɪkl/", "verb", "tái chế", "Residents should separate waste and recycle plastic containers.", "environment"),
    (213, "protect", "/prəˈtekt/", "verb", "bảo vệ, gìn giữ", "Strict laws are needed to protect endangered ecosystems.", "environment"),
    (214, "relationship", "/rɪˈleɪʃnʃɪp/", "noun", "mối quan hệ", "Open communication sustains a healthy, long-lasting relationship.", "social"),
    (215, "confidence", "/ˈkɑːnfɪdəns/", "noun", "sự tự tin", "Speaking aloud daily builds speaking confidence immensely.", "personal development"),
    (216, "curious", "/ˈkjʊriəs/", "adjective", "tò mò, ham hiểu biết", "Curious students constantly ask insightful questions.", "personality"),
    (217, "creative", "/kriˈeɪtɪv/", "adjective", "sáng tạo", "Design thinking inspires creative solutions to complex problems.", "personality"),
    (218, "independent", "/ˌɪndɪˈpendənt/", "adjective", "độc lập, tự chủ", "University encourages young adults to become independent thinkers.", "personal development"),
    (219, "reliable", "/rɪˈlaɪəbl/", "adjective", "đáng tin cậy", "She is a reliable teammate who always meets strict deadlines.", "personality"),
    (220, "ambitious", "/æmˈbɪʃəs/", "adjective", "có hoài bão, tham vọng", "Ambitious entrepreneurs strive to create groundbreaking ventures.", "career"),
    (221, "technology", "/tekˈnɑːlədʒi/", "noun", "công nghệ", "Technological advancements accelerate remote learning.", "technology"),
    (222, "software", "/ˈsɔːftwer/", "noun", "phần mềm", "This language-learning software incorporates spaced repetition.", "technology"),
    (223, "device", "/dɪˈvaɪs/", "noun", "thiết bị điện tử", "Smart devices allow continuous access to educational resources.", "technology"),
    (224, "connection", "/kəˈnekʃn/", "noun", "sự kết nối, liên lạc", "A stable internet connection is essential for video conferencing.", "technology"),
    (225, "privacy", "/ˈpraɪvəsi/", "noun", "quyền riêng tư", "Protecting user data privacy is crucial for online platforms.", "technology"),
    (226, "social media", "/ˈsoʊʃl ˈmiːdiə/", "noun", "mạng xã hội", "Limit social media usage to maintain productivity and mental focus.", "media"),
    (227, "influence", "/ˈɪnfluəns/", "verb", "ảnh hưởng, tác động", "Peer groups significantly influence teenage decision-making.", "society"),
    (228, "community", "/kəˈmjuːnəti/", "noun", "cộng đồng", "Volunteering helps cultivate a supportive local community.", "society"),
    (229, "volunteer", "/ˌvɑːlənˈtɪr/", "verb", "tình nguyện", "Many college students volunteer to teach English to underprivileged youth.", "society"),
    (230, "government", "/ˈɡʌvərnmənt/", "noun", "chính phủ", "The government introduced new incentives for renewable power.", "politics"),
    (231, "education", "/ˌedʒuˈkeɪʃn/", "noun", "nền giáo dục", "Quality education empowers individuals to overcome poverty.", "education"),
    (232, "university", "/ˌjuːnɪˈvɜːrsəti/", "noun", "trường đại học", "He graduated with honors from a reputable national university.", "education"),
    (233, "degree", "/dɪˈɡriː/", "noun", "bằng cấp học thuật", "A master's degree can unlock senior managerial roles.", "education"),
    (234, "scholarship", "/ˈskɑːlərʃɪp/", "noun", "học bổng", "She was awarded a full scholarship to study abroad in Canada.", "education"),
    (235, "certificate", "/sərˈtɪfɪkət/", "noun", "chứng chỉ", "He received an IELTS certificate with an overall band score of 8.0.", "education"),
    (236, "fluency", "/ˈfluːənsi/", "noun", "sự trôi chảy, lưu loát", "Shadowing techniques dramatically enhance spoken fluency.", "language"),
    (237, "pronunciation", "/prəˌnʌnsiˈeɪʃn/", "noun", "cách phát âm", "Accurate pronunciation ensures your message is clearly received.", "language"),
    (238, "accent", "/ˈæksent/", "noun", "chất giọng, ngữ điệu", "Every English accent has its own distinct rhythm and melody.", "language"),
    (239, "communication", "/kəˌmjuːnɪˈkeɪʃn/", "noun", "sự giao tiếp", "Effective communication prevents misunderstandings in the team.", "communication"),
    (240, "discussion", "/dɪˈskʌʃn/", "noun", "cuộc thảo luận", "The seminar fostered an engaging panel discussion on climate.", "communication"),
    (241, "presentation", "/ˌpriːzenˈteɪʃn/", "noun", "bài thuyết trình", "Her slide presentation captivated the entire board of directors.", "communication"),
    (242, "persuade", "/pərˈsweɪd/", "verb", "thuyết phục", "The speaker used persuasive data to persuade the skeptical audience.", "communication"),
    (243, "encourage", "/ɪnˈkɜːrɪdʒ/", "verb", "khuyến khích, động viên", "Good mentors always encourage their mentees to strive higher.", "personal development"),
    (244, "organize", "/ˈɔːrɡənaɪz/", "verb", "tổ chức, sắp xếp", "She organized all study materials into color-coded folders.", "productivity"),
    (245, "schedule", "/ˈskedʒuːl/", "noun", "lịch trình, thời gian biểu", "Keep a structured daily schedule to manage study hours wisely.", "productivity"),
    (246, "deadline", "/ˈdedlaɪn/", "noun", "hạn chót hoàn thành", "We worked overtime to deliver the project before the Friday deadline.", "productivity"),
    (247, "priority", "/praɪˈɔːrəti/", "noun", "sự ưu tiên", "Mastering core vocabulary should be your highest language priority.", "productivity"),
    (248, "achieve", "/əˈtʃiːv/", "verb", "đạt được, gặt hái", "Consistent daily effort is required to achieve high language goals.", "success"),
    (249, "success", "/səkˈses/", "noun", "sự thành công", "Patience and relentless discipline are hallmarks of lasting success.", "success"),
    (250, "failure", "/ˈfeɪljər/", "noun", "sự thất bại, bài học", "Treat failure as valuable feedback rather than a permanent defeat.", "mindset"),
    (251, "attitude", "/ˈætɪtuːd/", "noun", "thái độ, quan điểm", "A positive growth mindset transforms obstacles into learning milestones.", "mindset"),
    (252, "habit", "/ˈhæbɪt/", "noun", "thói quen", "Reading fifteen pages every morning soon becomes an effortless habit.", "mindset"),
    (253, "routine", "/ruːˈtiːn/", "noun", "lịch sinh hoạt thường nhật", "His morning routine consists of meditation, jogging, and vocabulary review.", "lifestyle"),
    (254, "nutrition", "/nuːˈtrɪʃn/", "noun", "chế độ dinh dưỡng", "Proper nutrition fuels cognitive function and physical vitality.", "health"),
    (255, "stress", "/stres/", "noun", "áp lực, căng thẳng", "Practicing deep breathing helps alleviate chronic work stress.", "health"),
    (256, "balance", "/ˈbæləns/", "noun", "sự cân bằng", "Strive for healthy balance between demanding study and rejuvenating rest.", "lifestyle"),
    (257, "entertainment", "/ˌentərˈteɪnmənt/", "noun", "hoạt động giải trí", "Watching English comedy shows doubles as educational entertainment.", "entertainment"),
    (258, "celebrate", "/ˈselɪbreɪt/", "verb", "ăn mừng, kỷ niệm", "Let's gather tonight to celebrate your test achievements.", "celebration"),
    (259, "tradition", "/trəˈdɪʃn/", "noun", "truyền thống phong tục", "Honoring cultural tradition strengthens familial bonds across generations.", "culture"),
    (260, "custom", "/ˈkʌstəm/", "noun", "tập quán, phong tục", "Learn local customs before traveling to a foreign country.", "culture"),
    (261, "society", "/səˈsaɪəti/", "noun", "xã hội", "A prosperous society invests generously in scientific research.", "society"),
    (262, "generation", "/ˌdʒenəˈreɪʃn/", "noun", "thế hệ", "The younger generation embraces digital technology instinctively.", "society"),
    (263, "population", "/ˌpɑːpjuˈleɪʃn/", "noun", "dân số", "Urban population growth accelerates the demand for green housing.", "society"),
    (264, "economy", "/ɪˈkɑːnəmi/", "noun", "nền kinh tế", "Tourism plays a pivotal role in invigorating the local economy.", "finance"),
    (265, "industry", "/ˈɪndəstri/", "noun", "ngành công nghiệp", "The software industry continues to expand exponentially worldwide.", "economy"),
    (266, "service", "/ˈsɜːrvɪs/", "noun", "dịch vụ", "Exceptional customer service fosters long-term client loyalty.", "business"),
    (267, "product", "/ˈprɑːdʌkt/", "noun", "sản phẩm", "Their team launched an innovative educational product last quarter.", "business"),
    (268, "customer", "/ˈkʌstəmər/", "noun", "khách hàng", "Always listen attentively to constructive feedback from your customers.", "business"),
    (269, "quality", "/ˈkwɑːləti/", "noun", "chất lượng", "Prioritize study quality over sheer quantity of study hours.", "descriptions"),
    (270, "quantity", "/ˈkwɑːntəti/", "noun", "số lượng", "Quality of vocabulary usage outweighs sheer quantity of memorized words.", "descriptions"),
    (271, "compare", "/kəmˈper/", "verb", "so sánh, đối chiếu", "Compare the nuances between these two synonymous expressions.", "analysis"),
    (272, "contrast", "/ˈkɑːntræst/", "verb", "tương phản, đối lập", "The essay contrasts traditional schooling with modern virtual learning.", "analysis"),
    (273, "describe", "/dɪˈskraɪb/", "verb", "mô tả chi tiết", "Can you vividly describe the setting of your favorite novel?", "communication"),
    (274, "express", "/ɪkˈspres/", "verb", "bày tỏ, diễn đạt", "Art enables people to express nuanced emotions beyond words.", "communication"),
    (275, "suggest", "/səɡˈdʒest/", "verb", "gợi ý, đề xuất", "Teachers often suggest using flashcards for spaced repetition.", "communication"),
    (276, "recommend", "/ˌrekəˈmend/", "verb", "khuyên bảo, giới thiệu", "I highly recommend this English podcast for intermediate learners.", "communication"),
    (277, "complain", "/kəmˈpleɪn/", "verb", "phàn nàn, khiếu nại", "Instead of complaining about hardship, formulate a practical action plan.", "communication"),
    (278, "apologize", "/əˈpɑːlədʒaɪz/", "verb", "xin lỗi chân thành", "He didn't hesitate to apologize sincerely for his unintentional oversight.", "politeness"),
    (279, "forgive", "/fərˈɡɪv/", "verb", "tha thứ, bao dung", "Learning to forgive past grievances brings inner tranquility.", "emotions"),
    (280, "promise", "/ˈprɑːmɪs/", "verb", "hứa hẹn", "She made a firm promise to study twenty new words every single day.", "communication"),
    (281, "discover", "/dɪˈskʌvər/", "verb", "khám phá, tìm ra", "Scientists continue to discover new species in deep ocean trenches.", "science"),
    (282, "invent", "/ɪnˈvent/", "verb", "phát minh", "Engineers invent innovative tools to simplify complex human tasks.", "science"),
    (283, "create", "/kriˈeɪt/", "verb", "tạo ra, sáng tạo", "Writers create immersive fictional worlds through evocative language.", "arts"),
    (284, "design", "/dɪˈzaɪn/", "verb", "thiết kế", "The architect designed an eco-friendly house powered by solar energy.", "arts"),
    (285, "produce", "/prəˈduːs/", "verb", "sản xuất, tạo thành", "This region produces the finest high-altitude Arabica coffee beans.", "economy"),
    (286, "consume", "/kənˈsuːm/", "verb", "tiêu thụ, hấp thụ", "Limit the amount of ultra-processed food you consume weekly.", "health"),
    (287, "increase", "/ɪnˈkriːs/", "verb", "tăng lên, gia tăng", "Regular reading substantially increases your active vocabulary reservoir.", "trends"),
    (288, "decrease", "/dɪˈkriːs/", "verb", "giảm xuống", "Consistent exercise helps decrease resting heart rate and blood pressure.", "trends"),
    (289, "develop", "/dɪˈveləp/", "verb", "phát triển, trau dồi", "It takes dedicated practice to develop high-level acoustic shadowing skills.", "growth"),
    (290, "manage", "/ˈmænɪdʒ/", "verb", "quản lý, xoay xở", "She managed to balance full-time employment with language mastery.", "productivity"),
    (291, "support", "/səˈpɔːrt/", "verb", "hỗ trợ, ủng hộ", "Family members support each other through life's trials and triumphs.", "relationships"),
    (292, "protect", "/prəˈtekt/", "verb", "bảo vệ, che chắn", "Sunscreen protects your skin from harmful ultraviolet rays.", "health"),
    (293, "prevent", "/prɪˈvent/", "verb", "ngăn ngừa, phòng tránh", "Early medical screenings help prevent serious health complications.", "health"),
    (294, "avoid", "/əˈvɔɪd/", "verb", "tránh né, né tránh", "Avoid multitasking when you are studying difficult grammar concepts.", "productivity"),
    (295, "admit", "/ədˈmɪt/", "verb", "thừa nhận", "It takes maturity to openly admit when you made an error in judgment.", "character"),
    (296, "deny", "/dɪˈnaɪ/", "verb", "chối bỏ, phủ nhận", "The witness did not deny seeing the incident unfold on the street.", "communication"),
    (297, "refuse", "/rɪˈfjuːz/", "verb", "từ chối", "He politely refused the invitation due to prior study commitments.", "communication"),
    (298, "accept", "/əkˈsept/", "verb", "chấp nhận, đón nhận", "Accept constructive feedback gracefully to accelerate skill mastery.", "mindset"),
    (299, "expect", "/ɪkˈspekt/", "verb", "kỳ vọng, trông đợi", "Don't expect overnight fluency; steady consistency yields genuine mastery.", "mindset"),
    (300, "imagine", "/ɪˈmædʒɪn/", "verb", "tưởng tượng, hình dung", "Imagine yourself speaking English fluently in front of a live audience.", "mindset")
]

b2_words = [
    (301, "collaborate", "/kəˈlæbəreɪt/", "verb", "hợp tác, cộng tác", "Cross-functional teams collaborate seamlessly to deploy web solutions.", "business"),
    (302, "negotiate", "/nɪˈɡoʊʃieɪt/", "verb", "đàm phán, thương lượng", "Skilled diplomats negotiate mutually beneficial trade treaties.", "business"),
    (303, "perspective", "/pərˈspektɪv/", "noun", "góc nhìn, quan điểm", "Living abroad offers a transformative global perspective on life.", "mindset"),
    (304, "significant", "/sɪɡˈnɪfɪkənt/", "adjective", "quan trọng, có ý nghĩa", "Daily spaced repetition yields significant cognitive retention gains.", "analysis"),
    (305, "comprehensive", "/ˌkɑːmprɪˈhensɪv/", "adjective", "toàn diện, bao quát", "This curriculum offers a comprehensive pathway from A1 to C2.", "education"),
    (306, "distinguish", "/dɪˈstɪŋɡwɪʃ/", "verb", "phân biệt, nhận định", "Learners must distinguish between subtle nuances in idiomatic usage.", "analysis"),
    (307, "sustainable", "/səˈsteɪnəbl/", "adjective", "bền vững", "Sustainable urban architecture reduces carbon footprints significantly.", "environment"),
    (308, "initiative", "/ɪˈnɪʃətɪv/", "noun", "sáng kiến, tính chủ động", "Taking personal initiative is the cornerstone of autonomous learning.", "career"),
    (309, "resilience", "/rɪˈzɪliəns/", "noun", "sự kiên cường, dẻo dai", "Mental resilience allows learners to overcome intermediate learning plateaus.", "psychology"),
    (310, "strategy", "/ˈstrætədʒi/", "noun", "chiến lược", "Employ an evidence-based vocabulary acquisition strategy.", "productivity"),
    (311, "efficient", "/ɪˈfɪʃnt/", "adjective", "hiệu quả, tối ưu", "SM-2 algorithmic review is an efficient memory consolidation method.", "productivity"),
    (312, "innovative", "/ˈɪnəveɪtɪv/", "adjective", "đổi mới, mang tính sáng kiến", "Innovative speech recognition models refine conversational accuracy.", "technology"),
    (313, "analyze", "/ˈænəlaɪz/", "verb", "phân tích thấu đáo", "Scholars analyze historical data to anticipate emerging market shifts.", "analysis"),
    (314, "evaluate", "/ɪˈvæljueɪt/", "verb", "đánh giá, thẩm định", "Rigorous teachers evaluate both spoken accuracy and idiomatic fluency.", "education"),
    (315, "demonstrate", "/ˈdemənstreɪt/", "verb", "chứng minh, thị phạm", "The experimental results clearly demonstrate the hypothesis.", "science"),
    (316, "fundamental", "/ˌfʌndəˈmentl/", "adjective", "cốt lõi, nền tảng", "Phonetic accuracy is fundamental to intelligible spoken English.", "linguistics"),
    (317, "alternative", "/ɔːlˈtɜːrnətɪv/", "noun", "sự lựa chọn thay thế", "Solar energy presents a viable alternative to fossil fuel power.", "environment"),
    (318, "consequence", "/ˈkɑːnsəkwens/", "noun", "hệ quả, hậu quả", "Ignoring sleep deprivation leads to severe cognitive consequences.", "health"),
    (319, "contribute", "/kənˈtrɪbjuːt/", "verb", "đóng góp, cống hiến", "Active student participation contributes to a dynamic classroom culture.", "social"),
    (320, "maintain", "/meɪnˈteɪn/", "verb", "duy trì, gìn giữ", "It requires daily dedication to maintain a sixty-day learning streak.", "habits"),
    (321, "establish", "/ɪˈstæblɪʃ/", "verb", "thiết lập, thành lập", "Establish a morning ritual dedicated to deliberate reading practice.", "habits"),
    (322, "emphasize", "/ˈemfəsaɪz/", "verb", "nhấn mạnh, làm nổi bật", "Linguists emphasize the vital role of contextual sentence acquisition.", "education"),
    (323, "potential", "/pəˈtenʃl/", "noun", "tiềm năng phát triển", "Every dedicated learner possesses the potential to achieve near-native fluency.", "personal development"),
    (324, "acquire", "/əˈkwaɪər/", "verb", "thu nhận, lĩnh hội", "Children acquire conversational grammar intuitively through immersion.", "linguistics"),
    (325, "fluctuate", "/ˈflʌktʃueɪt/", "verb", "dao động, lên xuống", "Currency exchange rates fluctuate in response to geopolitical volatility.", "finance"),
    (326, "eliminate", "/ɪˈlɪmɪneɪt/", "verb", "loại bỏ triệt để", "Systematic proofreading helps eliminate careless grammatical errors.", "writing"),
    (327, "facilitate", "/fəˈsɪlɪteɪt/", "verb", "tạo điều kiện thuận lợi", "Digital AI partners facilitate spontaneous bilingual voice practice.", "technology"),
    (328, "generate", "/ˈdʒenəreɪt/", "verb", "sản sinh, tạo ra", "Wind turbines generate clean electrical power for coastal communities.", "science"),
    (329, "indicate", "/ˈɪndɪkeɪt/", "verb", "chỉ ra, biểu thị", "Survey responses indicate strong enthusiasm for interactive learning apps.", "research"),
    (330, "interpret", "/ɪnˈtɜːrprət/", "verb", "diễn giải, thông dịch", "Translators must interpret idiomatic humor with nuanced cultural awareness.", "communication"),
    (331, "justify", "/ˈdʒʌstɪfaɪ/", "verb", "biện minh, chứng minh tính đúng đắn", "Can you justify your conclusion with verifiable statistical evidence?", "critical thinking"),
    (332, "modify", "/ˈmɑːdɪfaɪ/", "verb", "sửa đổi, điều chỉnh", "The engineer modified the prompt parameters to enhance response depth.", "technology"),
    (333, "participate", "/pɑːrˈtɪsɪpeɪt/", "verb", "tham gia tích cực", "Active learners participate eagerly in collaborative debate circles.", "education"),
    (334, "perceive", "/pərˈsiːv/", "verb", "nhận thức, cảm nhận", "How we perceive feedback dictates whether we grow or retreat.", "psychology"),
    (335, "reinforce", "/ˌriːɪnˈfɔːrs/", "verb", "củng cố, tăng cường", "Spaced interval quizzes reinforce synaptic connections in long-term memory.", "neuroscience"),
    (336, "transform", "/trænsˈfɔːrm/", "verb", "chuyển hóa, biến đổi", "Deliberate immersion can transform passive vocabulary into fluent speech.", "growth"),
    (337, "accommodate", "/əˈkɑːmədeɪt/", "verb", "đáp ứng, tạo chỗ cho", "Adaptive curricula accommodate diverse individual learning paces.", "education"),
    (338, "acknowledge", "/əkˈnɑːlɪdʒ/", "verb", "công nhận, ghi nhận", "Always acknowledge counter-arguments when drafting persuasive essays.", "writing"),
    (339, "anticipate", "/ænˈtɪsɪpeɪt/", "verb", "dự đoán, lường trước", "Seasoned debaters anticipate their opponents' points well in advance.", "critical thinking"),
    (340, "compensate", "/ˈkɑːmpənseɪt/", "verb", "bù đắp, đền bù", "Strong context clues compensate for occasionally unfamiliar lexical terms.", "reading"),
    (341, "contradict", "/ˌkɑːntrəˈdɪkt/", "verb", "mâu thuẫn, phản bác", "Empirical trial data contradict the previously held theoretical model.", "science"),
    (342, "deteriorate", "/dɪˈtɪriəreɪt/", "verb", "suy giảm, xuống cấp", "Without consistent active recall, foreign language fluency can deteriorate.", "memory"),
    (343, "differentiate", "/ˌdɪfəˈrenʃieɪt/", "verb", "phân biệt rạch ròi", "A C1 speaker can differentiate subtle shades of ironic expression.", "linguistics"),
    (344, "discriminate", "/dɪˈskrɪmɪneɪt/", "verb", "phân biệt đối xử / phân định", "The acoustic ear learns to discriminate between close vowel phonemes.", "linguistics"),
    (345, "incorporate", "/ɪnˈkɔːrpəreɪt/", "verb", "kết hợp, sáp nhập", "Modern educators incorporate multimedia podcasts into daily syllabi.", "education"),
    (346, "integrate", "/ˈɪntɪɡreɪt/", "verb", "tích hợp đồng bộ", "Seamlessly integrate voice synthesis into web-based language tools.", "technology"),
    (347, "manipulate", "/məˈnɪpjuleɪt/", "verb", "thao túng, điều khiển khéo léo", "Orators manipulate cadence and pitch to evoke emotional resonance.", "rhetoric"),
    (348, "overcome", "/ˌoʊvərˈkʌm/", "verb", "vượt qua nghịch cảnh", "Determination enables students to overcome stubborn pronunciation hurdles.", "personal development"),
    (349, "reconcile", "/ˈrekənsaɪl/", "verb", "hòa giải, dung hòa", "Diplomats worked tirelessly to reconcile divergent national interests.", "diplomacy"),
    (350, "stimulate", "/ˈstɪmjuleɪt/", "verb", "kích thích, thôi thúc", "Intellectually challenging articles stimulate neuroplastic cognitive growth.", "neuroscience"),
    (351, "adequate", "/ˈædɪkwət/", "adjective", "đầy đủ, thỏa đáng", "Ensure adequate hydration and restful sleep during intensive exam prep.", "health"),
    (352, "coherent", "/koʊˈhɪrənt/", "adjective", "mạch lạc, chặt chẽ", "A coherent essay demonstrates lucid transitions between paragraph premises.", "writing"),
    (353, "compatible", "/kəmˈpætəbl/", "adjective", "tương thích, hòa hợp", "Make sure the audio recording hardware is compatible with the web interface.", "technology"),
    (354, "deliberate", "/dɪˈlɪbərət/", "adjective", "có chủ đích, thận trọng", "Deliberate practice focuses specifically on correcting recurring weaknesses.", "learning"),
    (355, "diverse", "/daɪˈvɜːrs/", "adjective", "đa dạng, phong phú", "Reading diverse genres broadens semantic exposure across lexical fields.", "reading"),
    (356, "dynamic", "/daɪˈnæmɪk/", "adjective", "năng động, biến chuyển", "Language is a dynamic social organism that evolves continuously.", "linguistics"),
    (357, "flexible", "/ˈfleksəbl/", "adjective", "linh hoạt, uyển chuyển", "A flexible study schedule allows you to adapt to unexpected workloads.", "productivity"),
    (358, "inevitable", "/ɪnˈevɪtəbl/", "adjective", "không thể tránh khỏi", "Plateaus are an inevitable natural phase in any language journey.", "mindset"),
    (359, "inherent", "/ɪnˈhɪrənt/", "adjective", "vốn có, cố hữu", "There is an inherent beauty in deciphering foreign literary metaphors.", "philosophy"),
    (360, "mutual", "/ˈmjuːtʃuəl/", "adjective", "lẫn nhau, chung", "Mutual respect between speaker and listener fosters genuine dialogue.", "relationships"),
    (361, "plausible", "/ˈplɔːzəbl/", "adjective", "hợp lý, đáng tin", "The researcher offered a plausible hypothesis for the memory anomaly.", "science"),
    (362, "preliminary", "/prɪˈlɪmɪneri/", "adjective", "sơ bộ, ban đầu", "Preliminary diagnostic testing accurately benchmarks the student's level.", "education"),
    (363, "profound", "/prəˈfaʊnd/", "adjective", "sâu sắc, uyên thâm", "Reading classic literature imparts a profound appreciation for prose.", "literature"),
    (364, "rigorous", "/ˈrɪɡərəs/", "adjective", "nghiêm ngặt, khắt khe", "Rigorous acoustic shadowing drills condition articulate tongue mechanics.", "pronunciation"),
    (365, "sophisticated", "/səˈfɪstɪkeɪtɪd/", "adjective", "tinh tế, phức tạp cao cấp", "C2 speakers deploy sophisticated discourse markers to steer discussions.", "linguistics"),
    (366, "spontaneous", "/spɑːnˈteɪniəs/", "adjective", "tự nhiên, bộc phát", "Spontaneous conversation develops when fear of error is relinquished.", "speaking"),
    (367, "subtle", "/ˈsʌtl/", "adjective", "tinh tế, vi tế", "Pay close attention to subtle contextual differences between near-synonyms.", "linguistics"),
    (368, "unprecedented", "/ʌnˈpresɪdentɪd/", "adjective", "chưa từng có tiền lệ", "The digital era offers unprecedented access to authentic language corpora.", "technology"),
    (369, "versatile", "/ˈvɜːrsətl/", "adjective", "đa năng, linh hoạt", "Phrasal verbs are versatile lexical tools in conversational English.", "linguistics"),
    (370, "vulnerable", "/ˈvʌlnərəbl/", "adjective", "dễ bị tổn thương", "Coastal settlements are particularly vulnerable to rising sea levels.", "environment"),
    (371, "advocate", "/ˈædvəkeɪt/", "verb", "cổ vũ, tán thành", "Educators advocate for communicative language methodologies.", "education"),
    (372, "clarify", "/ˈklærəfaɪ/", "verb", "làm sáng tỏ", "Please clarify whether this assignment requires MLA or APA citation.", "communication"),
    (373, "enhance", "/ɪnˈhæns/", "verb", "nâng cao, trau dồi", "Extensive reading will organically enhance your expressive repertoire.", "growth"),
    (374, "illustrate", "/ˈɪləstreɪt/", "verb", "minh họa thực tế", "The author uses vivid real-world case studies to illustrate the thesis.", "communication"),
    (375, "presume", "/prɪˈzuːm/", "verb", "phỏng đoán, coi là", "Never presume you know a word's connotations without checking examples.", "linguistics"),
    (376, "restrict", "/rɪˈstrɪkt/", "verb", "hạn chế, giới hạn", "Do not restrict your practice solely to passive grammar exercises.", "learning"),
    (377, "sustain", "/səˈsteɪn/", "verb", "duy trì lâu bền", "Can you sustain focused cognitive effort across an hour-long exam?", "focus"),
    (378, "undertake", "/ˌʌndərˈteɪk/", "verb", "đảm nhận, dấn thân", "She decided to undertake the monumental task of reading Ulysses.", "ambition"),
    (379, "validate", "/ˈvælɪdeɪt/", "verb", "xác thực, phê chuẩn", "Automated code tests validate algorithmic accuracy and edge conditions.", "technology"),
    (380, "yield", "/jiːld/", "verb", "mang lại, sinh ra", "Consistent spaced repetition sessions yield immense vocabulary gains.", "growth"),
    (381, "paradox", "/ˈpærədɑːks/", "noun", "nghịch lý thú vị", "The fluency paradox is that speaking slowly often makes you sound faster.", "philosophy"),
    (382, "consensus", "/kənˈsensəs/", "noun", "sự đồng thuận chung", "Scientists reached broad consensus regarding anthropogenic warming.", "society"),
    (383, "criterion", "/kraɪˈtɪriən/", "noun", "tiêu chí đánh giá", "Acoustic naturalness is a key criterion in spoken exam scoring.", "assessment"),
    (384, "phenomenon", "/fəˈnɑːmɪnən/", "noun", "hiện tượng tự nhiên/xã hội", "Code-switching is a fascinating sociolinguistic phenomenon.", "linguistics"),
    (385, "dilemma", "/daɪˈlemə/", "noun", "tình thế tiến thoái lưỡng nan", "The committee faced an ethical dilemma concerning data privacy.", "ethics"),
    (386, "hierarchy", "/ˈhaɪərɑːrki/", "noun", "hệ thống cấp bậc", "Maslow's hierarchy illustrates fundamental layers of human motivation.", "psychology"),
    (387, "paradigm", "/ˈpærədaɪm/", "noun", "mô hình, hệ chuẩn", "AI-driven tutoring represents a fundamental paradigm shift in pedagogy.", "education"),
    (388, "spectrum", "/ˈspektrəm/", "noun", "phổ, dải rộng", "Learners exhibit competencies across a broad spectrum of aptitudes.", "science"),
    (389, "infrastructure", "/ˈɪnfrəstrʌktʃər/", "noun", "cơ sở hạ tầng", "Reliable digital infrastructure underpins modern online universities.", "technology"),
    (390, "discrepancy", "/dɪˈskrepənsi/", "noun", "sự chênh lệch, khác biệt", "Auditors detected a subtle discrepancy in the financial ledgers.", "finance"),
    (391, "hypothesis", "/haɪˈpɑːθəsɪs/", "noun", "giả thuyết khoa học", "Formulate a testable hypothesis before commencing laboratory trials.", "science"),
    (392, "equilibrium", "/ˌiːkwɪˈlɪbriəm/", "noun", "trạng thái cân bằng", "Strive for physiological and mental equilibrium amidst daily stress.", "health"),
    (393, "momentum", "/moʊˈmentəm/", "noun", "đà phát triển", "A thirty-day study streak creates unstoppable psychological momentum.", "motivation"),
    (394, "catalyst", "/ˈkætəlɪst/", "noun", "chất xúc tác, tác nhân thúc đẩy", "Curiosity is the prime catalyst for lifelong intellectual mastery.", "mindset"),
    (395, "ambiguity", "/ˌæmbɪˈɡjuːəti/", "noun", "tính mơ hồ, đa nghĩa", "Poetry deliberately exploits lexical ambiguity to invite varied readings.", "literature"),
    (396, "nuance", "/ˈnuːɑːns/", "noun", "sắc thái tinh tế", "A native speaker instinctively senses subtle nuances in vocal cadence.", "linguistics"),
    (397, "pragmatic", "/præɡˈmætɪk/", "adjective", "thực tế, thực dụng", "Adopt a pragmatic approach focused on communicative real-world utility.", "mindset"),
    (398, "lucid", "/ˈluːsɪd/", "adjective", "minh bạch, sáng tỏ", "The lecturer delivered a lucid exposition on structural linguistics.", "communication"),
    (399, "articulate", "/ɑːrˈtɪkjuleɪt/", "adjective", "lưu loát, ăn nói gãy gọn", "She is an articulate orator capable of moving audience sentiments.", "rhetoric"),
    (400, "tenacious", "/təˈneɪʃəs/", "adjective", "ngoan cường, bền bỉ", "A tenacious mindset guarantees success across grueling language exams.", "mindset")
]

c1_words = [
    (401, "quintessential", "/ˌkwɪntɪˈsenʃl/", "adjective", "tinh túy, mẫu mực", "Afternoon tea is considered the quintessential British cultural custom.", "culture"),
    (402, "ubiquitous", "/juːˈbɪkwɪtəs/", "adjective", "phổ biến khắp nơi", "Smartphones have become ubiquitous fixtures in modern metropolitan life.", "technology"),
    (403, "ephemeral", "/ɪˈfemərəl/", "adjective", "phù du, ngắn ngủi", "Fame in the digital age is often remarkably ephemeral and fleeting.", "philosophy"),
    (404, "corroborate", "/kəˈrɑːbəreɪt/", "verb", "chứng thực, củng cố", "Multiple independent witnesses corroborated the journalistic account.", "law"),
    (405, "benevolent", "/bəˈnevələnt/", "adjective", "nhân từ, thiện chí", "The benevolent philanthropist endowed university research laboratories.", "character"),
    (406, "pragmatism", "/ˈpræɡmətɪzəm/", "noun", "chủ nghĩa thực dụng", "His political philosophy was characterized by unyielding pragmatism.", "politics"),
    (407, "juxtapose", "/ˌdʒʌkstəˈpoʊz/", "verb", "đặt cạnh nhau để đối chiếu", "The documentary juxtaposes rural tranquility with chaotic urban sprawl.", "arts"),
    (408, "elucidate", "/ɪˈluːsɪdeɪt/", "verb", "làm sáng tỏ, giải thích sâu", "The professor took pains to elucidate the obscure mathematical theorem.", "academic"),
    (409, "mitigate", "/ˈmɪtɪɡeɪt/", "verb", "giảm nhẹ, xoa dịu", "Aggressive reforestation projects mitigate the severity of soil erosion.", "environment"),
    (410, "superfluous", "/suːˈpɜːrfluəs/", "adjective", "thừa thãi, không cần thiết", "Vigorous editing eliminates superfluous adjectives from academic prose.", "writing"),
    (411, "anomalous", "/əˈnɑːmələs/", "adjective", "dị thường, bất thường", "Scientists investigated the anomalous sensory data captured by satellites.", "science"),
    (412, "cogent", "/ˈkoʊdʒənt/", "adjective", "chặt chẽ, có sức thuyết phục", "She articulated a cogent legal defense that swayed the jury verdict.", "rhetoric"),
    (413, "esoteric", "/ˌesəˈterɪk/", "adjective", "thâm sâu, khó hiểu", "Quantum cryptography relies on esoteric mathematical principles.", "science"),
    (414, "meticulous", "/məˈtɪkjələs/", "adjective", "tỉ mỉ, cẩn trọng tuyệt đối", "The lexicographer conducted meticulous cross-referencing of archaic terms.", "research"),
    (415, "precocious", "/prɪˈkoʊʃəs/", "adjective", "sớm phát triển, thần đồng", "The precocious pianist mastered Chopin concertos at the tender age of ten.", "talent"),
    (416, "resplendent", "/rɪˈsplendənt/", "adjective", "lộng lẫy, rực rỡ", "The ceremonial ballroom was resplendent with crystal chandeliers and silk.", "descriptions"),
    (417, "tenacity", "/təˈnæsəti/", "noun", "sự bền bỉ, tính kiên định", "Her intellectual tenacity enabled her to solve the cryptographic puzzle.", "mindset"),
    (418, "vociferous", "/voʊˈsɪfərəs/", "adjective", "hò hét, phản đối ầm ĩ", "The proposed legislation drew vociferous protests from local unions.", "politics"),
    (419, "zealous", "/ˈzeləs/", "adjective", "hăng hái, nhiệt thành", "The zealous volunteers worked day and night distributing emergency rations.", "character"),
    (420, "acumen", "/əˈkjuːmən/", "noun", "sự nhạy bén, sắc sảo", "Her sharp business acumen guided the startup through market downturns.", "business"),
    (421, "alacrity", "/əˈlækrəti/", "noun", "sự sốt sắng, hăm hở", "The enthusiastic apprentice accepted the challenging task with alacrity.", "character"),
    (422, "belligerent", "/bəˈlɪdʒərənt/", "adjective", "hiếu chiến, gây hấn", "The belligerent stance of the border commander escalated diplomatic tension.", "diplomacy"),
    (423, "cacophony", "/kəˈkɑːfəni/", "noun", "âm thanh hỗn tạp chói tai", "A deafening cacophony of construction drills shattered morning quietude.", "senses"),
    (424, "deference", "/ˈdefərəns/", "noun", "sự tôn kính, nhún nhường", "The young barrister spoke with profound deference toward the presiding judge.", "etiquette"),
    (425, "egregious", "/ɪˈɡriːdʒəs/", "adjective", "nghiêm trọng quá đáng, trắng trợn", "Failing to check source authenticity was an egregious journalistic blunder.", "ethics"),
    (426, "fastidious", "/fæˈstɪdiəs/", "adjective", "kén chọn, kỹ tính tuyệt đối", "The chef maintained fastidious culinary standards in his three-star kitchen.", "character"),
    (427, "gregarious", "/ɡrɪˈɡeriəs/", "adjective", "thích giao du, hòa đồng", "Her gregarious temperament naturally attracted a wide circle of confidants.", "personality"),
    (428, "harangue", "/həˈræŋ/", "noun", "bài diễn thuyết nảy lửa, đao to búa lớn", "The fiery politician delivered a lengthy harangue against corporate tax evasion.", "politics"),
    (429, "iconoclast", "/aɪˈkɑːnəklæst/", "noun", "người bài trừ thần tượng, phá vỡ lối mòn", "The visionary director was hailed as an iconoclast who reinvented cinematic narrative.", "arts"),
    (430, "judicious", "/dʒuːˈdɪʃəs/", "adjective", "sáng suốt, biết suy xét", "Through judicious financial management, the academy avoided insolvency.", "wisdom"),
    (431, "laconic", "/ləˈkɑːnɪk/", "adjective", "ngắn gọn súc tích, ít lời", "The philosopher was famed for his dry wit and laconic rejoinders.", "communication"),
    (432, "magnanimous", "/mæɡˈnænɪməs/", "adjective", "hào hiệp, độ lượng cao thượng", "In a magnanimous gesture, the victorious contender praised his rival.", "character"),
    (433, "nefarious", "/nɪˈferiəs/", "adjective", "hung ác, bất chính", "Cybersecurity detectives thwarted the hacker syndicate's nefarious extortion scheme.", "crime"),
    (434, "obsequious", "/əbˈsiːkwiəs/", "adjective", "khúm núm, xu nịnh", "The arrogant emperor was perpetually surrounded by obsequious courtiers.", "character"),
    (435, "panacea", "/ˌpænəˈsiːə/", "noun", "phương thuốc vạn năng", "Technological disruption is an engine of progress, not an absolute societal panacea.", "philosophy"),
    (436, "quandary", "/ˈkwɑːndəri/", "noun", "tình thế bối rối khó xử", "The university administration found itself in a delicate legal quandary.", "challenges"),
    (437, "recalcitrant", "/rɪˈkælsɪtrənt/", "adjective", "ngoan cố, chống đối", "The recalcitrant committee member steadfastly refused to ratify the charter.", "politics"),
    (438, "sagacious", "/səˈɡeɪʃəs/", "adjective", "thông thái, sắc sảo", "The elder statesman provided sagacious counsel during the geopolitical crisis.", "wisdom"),
    (439, "taciturn", "/ˈtæsɪtɜːrn/", "adjective", "lầm lì, ít nói", "The detective was notoriously taciturn, preferring keen observation to discourse.", "personality"),
    (440, "unctuous", "/ˈʌŋktʃuəs/", "adjective", "giả tạo ngọt ngào, xảo trá", "His unctuous charm failed to deceive the discerning selection board.", "character"),
    (441, "venerate", "/ˈvenəreɪt/", "verb", "tôn sùng, kính cẩn", "Traditional cultures venerate ancestors through solemn seasonal rites.", "culture"),
    (442, "wary", "/ˈweri/", "adjective", "cảnh giác, dè chừng", "Seasoned investors remain wary of speculative assets with erratic valuations.", "finance"),
    (443, "zenith", "/ˈziːnɪθ/", "noun", "đỉnh cao, cực thịnh", "The Roman Empire reached its political and territorial zenith in the second century.", "history"),
    (444, "aberration", "/ˌæbəˈreɪʃn/", "noun", "sự trệch hướng, dị biệt", "The sudden temperature plunge was considered an unprecedented meteorological aberration.", "science"),
    (445, "bombastic", "/bɑːmˈbæstɪk/", "adjective", "khoa trương, sáo rỗng", "The critic dismissed the debut novel as a bombastic exercise in vanity.", "criticism"),
    (446, "candid", "/ˈkændɪd/", "adjective", "thẳng thắn, bộc trực", "She gave a refreshingly candid evaluation of the firm's strategic vulnerabilities.", "communication"),
    (447, "deleterious", "/ˌdeləˈtɪriəs/", "adjective", "có hại, độc hại", "Chronic sleep deprivation exerts a deleterious impact on memory recall.", "health"),
    (448, "eloquent", "/ˈeləkwənt/", "adjective", "hùng hồn, truyền cảm", "The civil rights leader delivered an eloquent plea for racial harmony.", "rhetoric"),
    (449, "foster", "/ˈfɑːstər/", "verb", "nuôi dưỡng, thúc đẩy", "Collaborative project environments foster creative lateral thinking.", "education"),
    (450, "germane", "/dʒɜːrˈmeɪn/", "adjective", "thích hợp, có liên quan chặt chẽ", "Please restrict your queries to issues germane to today's agenda.", "academic"),
    (451, "hedonist", "/ˈhiːdənɪst/", "noun", "người theo chủ nghĩa khoái lạc", "The dissolute nobleman lived as an unabashed hedonist in renaissance Florence.", "philosophy"),
    (452, "immutable", "/ɪˈmjuːtəbl/", "adjective", "bất biến, không thể thay đổi", "The fundamental laws of thermodynamics are considered immutable principles of physics.", "science"),
    (453, "judiciously", "/dʒuːˈdɪʃəsli/", "adverb", "một cách khôn ngoan sáng suốt", "Allocate study hours judiciously across grammatical, auditory, and vocal drills.", "productivity"),
    (454, "kinetic", "/kɪˈnetɪk/", "adjective", "thuộc về động năng, chuyển động", "The choreography burst with kinetic vitality and spellbinding poise.", "arts"),
    (455, "laudable", "/ˈlɔːdəbl/", "adjective", "đáng khen ngợi, tán dương", "Her tireless dedication to adult literacy education is truly laudable.", "ethics"),
    (456, "malleable", "/ˈmæliəbl/", "adjective", "dễ uốn nắn, mềm dẻo", "Young neural synapses are remarkably malleable during immersive linguistic acquisition.", "neuroscience"),
    (457, "nonchalant", "/ˌnɑːnʃəˈlɑːnt/", "adjective", "thờ ơ, thản nhiên bình thản", "He maintained an impeccably nonchalant exterior despite inner trepidation.", "demeanor"),
    (458, "opaque", "/oʊˈpeɪk/", "adjective", "mờ đục, khó hiểu tối nghĩa", "The bureaucratic regulations were drafted in unnecessarily opaque legalese.", "communication"),
    (459, "partisan", "/ˈpɑːrtəzn/", "adjective", "mang tính phe phái, thiên vị", "The editorial was criticized for adopting an overtly partisan stance.", "politics"),
    (460, "quell", "/kwel/", "verb", "dập tắt, xoa dịu", "The emergency central bank rate cut helped quell panicky financial markets.", "finance"),
    (461, "rancor", "/ˈræŋkər/", "noun", "sự thù hằn cay đắng", "The bitter rivals concluded their protracted debate without lingering rancor.", "emotions"),
    (462, "salient", "/ˈseɪliənt/", "adjective", "nổi bật, cốt yếu", "Summarize the most salient arguments presented in the doctoral dissertation.", "academic"),
    (463, "tenuous", "/ˈtenjuəs/", "adjective", "mong manh, yếu ớt", "The historical link between the two archaeological artifacts remains tenuous.", "history"),
    (464, "ubiquity", "/juːˈbɪkwəti/", "noun", "sự có mặt khắp nơi", "The ubiquity of broadband access has democratized global academic scholarship.", "technology"),
    (465, "vacillate", "/ˈvæsəleɪt/", "verb", "do dự, dao động", "Do not vacillate between study techniques; commit wholeheartedly to deliberate repetition.", "mindset"),
    (466, "wane", "/weɪn/", "verb", "suy tàn, giảm dần", "Public interest in the sensationalized tabloid headline began to wane.", "trends"),
    (467, "xenophobia", "/ˌzenəˈfoʊbiə/", "noun", "chứng bài ngoại, sợ người lạ", "Cosmopolitan education combats xenophobia through cultural exchange.", "society"),
    (468, "yielding", "/ˈjiːldɪŋ/", "adjective", "dễ dãi, chịu phục tùng", "His accommodating and yielding disposition made him well-liked in diplomacy.", "character"),
    (469, "zeal", "/ziːl/", "noun", "lòng nhiệt huyết say mê", "She attacked the formidable linguistic syllabus with unmatched scholarly zeal.", "motivation"),
    (470, "adroit", "/əˈdrɔɪt/", "adjective", "khéo léo, tài tình", "The negotiator proved adroit at reconciling deeply polarized ideologies.", "diplomacy"),
    (471, "boisterous", "/ˈbɔɪstərəs/", "adjective", "náo nhiệt, ầm ĩ vui vẻ", "The boisterous stadium erupted into deafening cheers as the goal was scored.", "society"),
    (472, "circumspect", "/ˈsɜːrkəmspekt/", "adjective", "thận trọng, nhìn trước ngó sau", "Diplomats must remain circumspect when addressing delicate sovereign borders.", "politics"),
    (473, "dearth", "/dɜːrθ/", "noun", "sự khan hiếm, thiếu hụt", "There was an acute dearth of empirical evidence supporting the radical hypothesis.", "science"),
    (474, "effervescent", "/ˌefərˈvesnt/", "adjective", "sôi nổi, tràn đầy sức sống", "Her effervescent wit enlivened even the most tedious committee deliberations.", "personality"),
    (475, "frenetic", "/frəˈnetɪk/", "adjective", "cuồng loạn, hối hả điên cuồng", "The stock exchange floor descended into frenetic trading before the bell.", "finance"),
    (476, "gratuitous", "/ɡrəˈtuːɪtəs/", "adjective", "vô cớ, không có lý do chính đáng", "The critic denounced the movie for containing gratuitous cinematic violence.", "arts"),
    (477, "hapless", "/ˈhæpləs/", "adjective", "bất hạnh, không may", "The hapless tourists lost their luggage during the transatlantic connection.", "misfortune"),
    (478, "impetuous", "/ɪmˈpetʃuəs/", "adjective", "bốc đồng, hấp tấp", "Impetuous decisions driven by sudden passion often incur severe remorse.", "character"),
    (479, "juxtaposition", "/ˌdʒʌkstəpəˈzɪʃn/", "noun", "sự đặt cạnh nhau đối lập", "The artistic juxtaposition of ancient ruins against neon skyscrapers is striking.", "arts"),
    (480, "kindle", "/ˈkɪndl/", "verb", "thắp lên, nhóm lên", "A charismatic teacher can kindle a lifelong passion for academic inquiry.", "inspiration"),
    (481, "lament", "/ləˈment/", "verb", "than thở, tiếc nuối", "Scholars often lament the erosion of minority dialects in a globalized era.", "culture"),
    (482, "morose", "/məˈroʊs/", "adjective", "rầu rĩ, ủ rũ khó tính", "The defeated commander sat in morose silence inside the military tent.", "emotions"),
    (483, "neophyte", "/ˈniːəfaɪt/", "noun", "người mới vào nghề, lính mới", "Even a neophyte programmer can quickly learn fundamental syntax conventions.", "career"),
    (484, "obdurate", "/ˈɑːbdərət/", "adjective", "ngoan cố, chai lì không lay chuyển", "Despite impassioned pleas, the monarch remained obdurate and inflexible.", "politics"),
    (485, "parsimonious", "/ˌpɑːrsɪˈmoʊniəs/", "adjective", "keo kiệt, bủn xỉn", "The parsimonious landlord refused to fund critical structural repairs.", "finance"),
    (486, "quandaries", "/ˈkwɑːndəriz/", "noun", "những nỗi băn khoăn khó xử", "Moral quandaries form the narrative core of classic tragic drama.", "literature"),
    (487, "reprehensible", "/ˌreprɪˈhensəbl/", "adjective", "đáng bị lên án, đáng trách", "Plagiarizing academic source material is fundamentally reprehensible conduct.", "ethics"),
    (488, "spurious", "/ˈspjuːriəs/", "adjective", "giả mạo, sai lệch ngụy tạo", "The investigative committee dismissed the leaked memo as entirely spurious.", "journalism"),
    (489, "trepidation", "/ˌtrepɪˈdeɪʃn/", "noun", "sự âu lo thắc thỏm", "She stepped onto the symposium dais with palpable trepidation.", "emotions"),
    (490, "unassailable", "/ˌʌnəˈseɪləbl/", "adjective", "không thể công kích, vững như bàn thạch", "Her experimental logic was constructed on unassailable statistical data.", "science"),
    (491, "venerable", "/ˈvenərəbl/", "adjective", "đáng kính, tôn kính bởi tuổi tác/đức độ", "The venerable professor retired after fifty illustrious years of research.", "people"),
    (492, "whimsical", "/ˈwɪmzɪkl/", "adjective", "kỳ quặc hài hước, thất thường", "The children's fantasy novel delighted audiences with its whimsical prose.", "literature"),
    (493, "abnegation", "/ˌæbnɪˈɡeɪʃn/", "noun", "sự từ bỏ quyền lợi, hy sinh", "Monastic orders are traditionally grounded in ascetic spiritual abnegation.", "philosophy"),
    (494, "beguile", "/bɪˈɡaɪl/", "verb", "mê hoặc, quyến rũ đánh lừa", "The con artist used silver-tongued rhetoric to beguile unwary investors.", "communication"),
    (495, "connoisseur", "/ˌkɑːnəˈsɜːr/", "noun", "người sành sỏi, am hiểu", "As a connoisseur of classical poetry, he analyzed every metrical foot.", "arts"),
    (496, "disparate", "/ˈdɪspərət/", "adjective", "khác biệt hoàn toàn, tạp nhạp", "The coalition synthesized disparate political agendas into a unified manifesto.", "politics"),
    (497, "equanimity", "/ˌiːkwəˈnɪməti/", "noun", "sự bình thản, điềm tĩnh", "A true leader confronts unforeseen adversity with unshakeable equanimity.", "stoicism"),
    (498, "fulsome", "/ˈfʊlsəm/", "adjective", "thái quá, nịnh hót quá đà", "The candidate's fulsome self-praise alienated moderate swing voters.", "politics"),
    (499, "garrulous", "/ˈɡærələs/", "adjective", "ba hoa, lắm mồm", "The garrulous cab driver entertained his passenger with neighborhood lore.", "personality"),
    (500, "hubris", "/ˈhjuːbrɪs/", "noun", "sự kiêu ngạo quá đỗi", "Ancient Greek tragedies caution against the fatal hubris of mortal kings.", "literature")
]

c2_words = [
    (501, "sesquipedalian", "/ˌseskwɪpɪˈdeɪliən/", "adjective", "sử dụng từ ngữ dài dòng phức tạp", "His sesquipedalian prose style often obscured rather than clarified his philosophical thesis.", "linguistics"),
    (502, "perspicacious", "/ˌpɜːrspɪˈkeɪʃəs/", "adjective", "sáng suốt, minh mẫn sâu sắc", "The perspicacious political analyst accurately forecasted the constitutional impasse.", "wisdom"),
    (503, "lugubrious", "/luːˈɡuːbriəs/", "adjective", "buồn thảm, u sầu bi ai", "The cellist produced a lugubrious melody that resonated throughout the solemn cathedral.", "arts"),
    (504, "antediluvian", "/ˌæntidɪˈluːviən/", "adjective", "cổ lỗ sĩ, tiền hồng thủy", "The professor derided the institution's antediluvian administrative procedures.", "history"),
    (505, "grandiloquent", "/ɡrænˈdɪləkwənt/", "adjective", "hoa mỹ sáo rỗng, đại ngôn", "The ambassador dismissed his counterpart's grandiloquent rhetoric as mere political theater.", "rhetoric"),
    (506, "perfunctory", "/pərˈfʌŋktəri/", "adjective", "lấy lệ, chiếu lệ hời hợt", "He offered a perfunctory nod of acknowledgment before returning to his monograph.", "behavior"),
    (507, "ineffable", "/ɪnˈefəbl/", "adjective", "không thể diễn tả bằng lời", "Gazing upon the aurora borealis instilled an ineffable sense of cosmic wonder.", "feelings"),
    (508, "intransigent", "/ɪnˈtrænsədʒənt/", "adjective", "không khoan nhượng, ngoan cố", "The labor negotiations collapsed due to the intransigent stance of both factions.", "diplomacy"),
    (509, "propinquity", "/prəˈpɪŋkwəti/", "noun", "sự gần gũi về không gian / họ hàng", "Physical propinquity often catalyzes spontaneous cross-disciplinary collaboration.", "sociology"),
    (510, "surreptitious", "/ˌsɜːrəpˈtɪʃəs/", "adjective", "lén lút, vụng trộm", "The undercover operative made a surreptitious exchange of encrypted microfilm.", "espionage"),
    (511, "pusillanimous", "/ˌpjuːsɪˈlænɪməs/", "adjective", "hèn nhát, nhút nhát đớn hèn", "The parliament decried the premier's pusillanimous capitulation to foreign coercion.", "politics"),
    (512, "recondite", "/ˈrekəndaɪt/", "adjective", "uyên thâm, ẩn khuất khó hiểu", "The theological treatise explored recondite doctrines of medieval hermeneutics.", "academic"),
    (513, "salubrious", "/səˈluːbriəs/", "adjective", "lành mạnh, tốt cho sức khỏe", "The crisp alpine climate exerted a remarkably salubrious effect on his convalescence.", "health"),
    (514, "trenchant", "/ˈtrentʃənt/", "adjective", "sắc bén, đanh thép sâu cay", "Her trenchant critique dismantled the economic orthodoxy championed by the establishment.", "criticism"),
    (515, "vicissitude", "/vɪˈsɪsɪtuːd/", "noun", "sự thăng trầm của cuộc đời", "A stoic philosopher endures the unpredictable vicissitudes of fortune with equanimity.", "philosophy"),
    (516, "pulchritude", "/ˈpʌlkrɪtuːd/", "noun", "vẻ đẹp lộng lẫy mỹ miều", "Renaissance portraiture celebrated radiant feminine pulchritude in delicate tempera.", "aesthetics"),
    (517, "quisling", "/ˈkwɪzlɪŋ/", "noun", "kẻ phản quốc, tay sai bán nước", "Historical annals revile the treacherous quisling who betrayed his besieged countrymen.", "history"),
    (518, "supercilious", "/ˌsuːpərˈsɪliəs/", "adjective", "kiêu kỳ, khinh khỉnh ngạo mạn", "The aristocrat surveyed the commoners with a haughty, supercilious smirk.", "demeanor"),
    (519, "tergiversate", "/tɜːrˈdʒɪvərseɪt/", "verb", "lật lọng, tráo trở lập trường", "Cornered by investigative journalists, the evasive senator began to tergiversate.", "politics"),
    (520, "uxorious", "/ʌkˈsɔːriəs/", "adjective", "quá nuông chiều vợ, si vợ", "The uxorious monarch lavished royal jewels and estates upon his beloved consort.", "relationships"),
    (521, "vituperate", "/vaɪˈtuːpəreɪt/", "verb", "chửi bới thậm tệ, thóa mạ", "Enraged partisans vituperate against political apostates on social forums.", "politics"),
    (522, "welter", "/ˈweltər/", "noun", "mớ hỗn độn ngổn ngang", "The symposium proceedings drowned in a confusing welter of conflicting statistics.", "disorder"),
    (523, "xenial", "/ˈziːniəl/", "adjective", "hiếu khách, thuận tình đãi khách", "Ancient Hellenic culture revered the sacred xenial bonds connecting host and guest.", "culture"),
    (524, "yoke", "/joʊk/", "noun", "ách thống trị, gông cùm", "The liberation movement sought to cast off the oppressive yoke of colonial despotism.", "history"),
    (525, "zeitgeist", "/ˈtsaɪtɡaɪst/", "noun", "tinh thần thời đại", "Dystopian fiction in the nineteen-thirties captured the anxious European zeitgeist.", "culture"),
    (526, "adumbrate", "/ˈædəmbreɪt/", "verb", "phác thảo lờ mờ, báo trước", "The introductory chapter serves to adumbrate the overarching themes of the epic.", "literature"),
    (527, "bilious", "/ˈbɪliəs/", "adjective", "cáu kỉnh, gắt gỏng cay độc", "The columnist was notorious for his bilious diatribes against avant-garde architecture.", "temperament"),
    (528, "cunctator", "/kʌŋkˈteɪtər/", "noun", "kẻ trì hoãn có toan tính", "Like Fabius Cunctator, the general chose tactical delay over reckless battlefield engagement.", "strategy"),
    (529, "defenestration", "/diːˌfenəˈstreɪʃn/", "noun", "sự ném qua cửa sổ / hạ bệ chức vụ", "The Defenestration of Prague ignited the devastating conflagration of the Thirty Years' War.", "history"),
    (530, "ebullient", "/ɪˈbʊliənt/", "adjective", "sôi sục hân hoan, rạng rỡ", "Her ebullient laughter reverberated through the hushed chambers of the cloistered academy.", "emotions"),
    (531, "factotum", "/fækˈtoʊtəm/", "noun", "người gánh vác mọi việc (tay sai đa năng)", "The elderly butler served as an indispensable factotum running the entire country estate.", "people"),
    (532, "gossamer", "/ˈɡɑːsəmər/", "adjective", "mỏng như tơ nhện, thanh thoát", "The bride wore an ethereal veil fashioned from gossamer French lace.", "aesthetics"),
    (533, "histrionic", "/ˌhɪstriˈɑːnɪk/", "adjective", "kịch cỡm, làm bộ làm tịch", "Her histrionic outbursts during court proceedings exasperated the presiding magistrate.", "behavior"),
    (534, "inchoate", "/ɪnˈkoʊət/", "adjective", "mới phôi thai, chưa định hình", "The manifesto laid out inchoate visions of socioeconomic restructuring.", "philosophy"),
    (535, "jejune", "/dʒɪˈdʒuːn/", "adjective", "nhạt nhẽo, ấu trĩ thiếu chiều sâu", "Critics lambasted the sophomore screenplay as jejune, derivative, and emotionally shallow.", "criticism"),
    (536, "ken", "/ken/", "noun", "tầm hiểu biết, tầm mắt", "The intricacies of string cosmology lie far beyond the ken of casual lay observers.", "knowledge"),
    (537, "limpid", "/ˈlɪmpɪd/", "adjective", "trong vắt, sáng rõ minh bạch", "The philosopher expressed metaphysical paradoxes in remarkably limpid and elegant prose.", "writing"),
    (538, "mordant", "/ˈmɔːrdnt/", "adjective", "châm biếm sâu cay, cay độc", "The political satirist wielded a mordant wit that punctured governmental pretension.", "satire"),
    (539, "nadir", "/ˈneɪdɪr/", "noun", "điểm thấp nhất, đáy vực sâu", "The collapse of the national currency marked the economic nadir of the republic.", "history"),
    (540, "opprobrium", "/əˈproʊbriəm/", "noun", "sự sỉ nhục, tiếng xấu muôn đời", "The disgraced oligarch faced universal public opprobrium following the embezzlement trial.", "ethics"),
    (541, "panegyric", "/ˌpænəˈdʒɪrɪk/", "noun", "bài ca tụng nhiệt liệt", "The laureate composed an eloquent panegyric honoring the fallen heroes of the revolution.", "literature"),
    (542, "querulous", "/ˈkwerələs/", "adjective", "hay càu nhàu, than phiền cáu kỉnh", "The querulous patient incessantly berated the attending nursing staff throughout the night.", "temperament"),
    (543, "redolent", "/ˈredələnt/", "adjective", "ngát hương / gợi nhớ sâu sắc", "The antique cedar trunk was redolent with memories of bygone maritime voyages.", "senses"),
    (544, "sybarite", "/ˈsɪbəraɪt/", "noun", "kẻ ham mê xa xỉ khoái lạc", "The decadent Roman patrician lived as an unapologetic sybarite in his Baiae villa.", "lifestyle"),
    (545, "truculent", "/ˈtrʌkjələnt/", "adjective", "hung hăng ngỗ ngược, hiếu chiến", "The boxer fixed his opponent with a truculent gaze across the weigh-in platform.", "behavior"),
    (546, "unbridled", "/ʌnˈbraɪdld/", "adjective", "không bị kiềm chế, bạt mạng", "His unbridled ambition eventually precipitated his catastrophic political downfall.", "psychology"),
    (547, "verisimilitude", "/ˌverɪsɪˈmɪlɪtuːd/", "noun", "tính chân thực như đời sống", "The historical novelist achieved breathtaking verisimilitude through archival research.", "literature"),
    (548, "wraith", "/reɪθ/", "noun", "bóng ma, bóng hình thoắt ẩn", "A solitary figure drifted through the nocturnal mist like an ephemeral wraith.", "imagery"),
    (549, "xanthic", "/ˈzænθɪk/", "adjective", "có màu vàng hoặc hơi vàng", "Autumnal birch leaves shed their vibrant xanthic foliage across the mountain pass.", "nature"),
    (550, "yonder", "/ˈjɑːndər/", "adverb", "ở đằng kia (văn học/cổ điển)", "Look to yonder distant horizon where storm clouds gather over the sea.", "literature"),
    (551, "zephyr", "/ˈzefər/", "noun", "làn gió nhẹ ấm áp", "A gentle fragrant zephyr rustled the lavender blossoms along the Provençal hillside.", "nature"),
    (552, "apotheosis", "/əˌpɑːθiˈoʊsɪs/", "noun", "sự tôn sùng đỉnh cao, sự thần thánh hóa", "Beethoven's Ninth Symphony stands as the sublime apotheosis of classical symphonic form.", "arts"),
    (553, "bathycolpian", "/ˌbæθɪˈkɑːlpiən/", "adjective", "nở nang, có dáng ngực sâu (văn thơ cổ)", "Homeric hymns immortalized bathycolpian maidens dancing upon Delian shores.", "literature"),
    (554, "chimerical", "/kaɪˈmɪrɪkl/", "adjective", "ảo tưởng, hão huyền không thực tế", "His grand scheme for universal perpetual motion proved hopelessly chimerical.", "science"),
    (555, "diaphanous", "/daɪˈæfənəs/", "adjective", "mỏng manh mờ ảo, trong suốt", "The dancer was veiled in diaphanous gossamer silks that billowed with each arabesque.", "arts"),
    (556, "eleemosynary", "/ˌelɪˈmɑːsəneri/", "adjective", "thuộc về từ thiện, nhân đạo", "The aristocratic family channeled substantial wealth into eleemosynary trusts.", "society"),
    (557, "frangible", "/ˈfrændʒəbl/", "adjective", "dễ vỡ, giòn gãy", "Handle the antique porcelain relic with supreme care as its glaze is highly frangible.", "objects"),
    (558, "gemütlichkeit", "/ɡəˈmjuːtlɪçkaɪt/", "noun", "cảm giác ấm cúng, thân tình dễ chịu", "The Bavarian tavern radiated an unmistakable ambiance of rustic gemütlichkeit.", "culture"),
    (559, "hegemony", "/hɪˈdʒeməni/", "noun", "quyền bá chủ, ưu thế tuyệt đối", "The superpower sought to maintain economic and naval hegemony over the shipping straits.", "geopolitics"),
    (560, "insouciance", "/ɪnˈsuːsiəns/", "noun", "sự thản nhiên không màng âu lo", "With characteristic insouciance, the seasoned daredevil shrugged off the perilous danger.", "temperament"),
    (561, "jejunity", "/dʒɪˈdʒuːnəti/", "noun", "sự tẻ nhạt nghèo nàn, cạn kiệt ý tưởng", "Scholars deplored the utter jejunity of contemporary mass market television programming.", "criticism"),
    (562, "kakistocracy", "/ˌkækɪˈstɑːkrəsi/", "noun", "chính phủ của những kẻ tồi tệ nhất", "Satirical commentators decried the corrupt regime as an archetypal kakistocracy.", "politics"),
    (563, "labyrinthine", "/ˌlæbəˈrɪnθɪn/", "adjective", "như mê cung, chằng chịt rắc rối", "Navigating the labyrinthine alleys of the ancient bazaar required an experienced guide.", "places"),
    (564, "mellifluous", "/meˈlɪfluəs/", "adjective", "ngọt ngào êm dịu, rót mật vào tai", "Her mellifluous soprano voice captivated every listener seated in the opera house.", "music"),
    (565, "numinous", "/ˈnuːmɪnəs/", "adjective", "thiêng liêng thần bí, gợi kính sợ", "Standing within the cavernous Gothic nave evoked an overwhelmingly numinous silence.", "spirituality"),
    (566, "oneiric", "/oʊˈnaɪrɪk/", "adjective", "thuộc về giấc mơ, mang tính ảo mộng", "The surrealist masterpiece plunged viewers into an oneiric landscape of melting clocks.", "arts"),
    (567, "panoply", "/ˈpænəpli/", "noun", "bộ sưu tập tráng lệ, giáp trụ lộng lẫy", "The state gala displayed a resplendent panoply of diplomatic military decorations.", "ceremony"),
    (568, "quaff", "/kwɑːf/", "verb", "uống ừng ực, cạn chén say sưa", "The victorious Norse warriors gathered in the mead hall to quaff foamy ales.", "celebration"),
    (569, "riparian", "/raɪˈperiən/", "adjective", "thuộc về ven bờ sông", "The ecological sanctuary preserves vital riparian habitats for endangered amphibians.", "nature"),
    (570, "solipsism", "/ˈsɑːlɪpsɪzəm/", "noun", "chủ nghĩa duy ngã", "Epistemological solipsism argues that the self is the only entity knowable with certainty.", "philosophy"),
    (571, "tintinnabulation", "/ˌtɪntɪˌnæbjuˈleɪʃn/", "noun", "tiếng chuông ngân vang rộn rã", "Poe's verses immortalized the melodious tintinnabulation of distant silver bells.", "poetry"),
    (572, "umbrage", "/ˈʌmbrɪdʒ/", "noun", "sự phật ý, tức tối", "The sensitive diplomat took acute umbrage at the unauthorized disclosure of the cable.", "etiquette"),
    (573, "verisimilar", "/ˌverɪˈsɪmɪlər/", "adjective", "có vẻ thật, đáng tin cậy", "The CGI rendering was so verisimilar that audiences could not detect digital artifice.", "cinema"),
    (574, "weltanschauung", "/ˈveltˌɑːnʃaʊ.ʊŋ/", "noun", "thế giới quan toàn diện", "His profound scientific weltanschauung harmonized empirical rigour with poetic awe.", "philosophy"),
    (575, "xanthous", "/ˈzænθəs/", "adjective", "vàng hoe (tóc), màu vàng sáng", "The Nordic folklore depicted fairy maidens crowned with long, shimmering xanthous tresses.", "literature"),
    (576, "yeoman", "/ˈjoʊmən/", "noun", "người làm việc mẫn cán tận tụy", "The chief engineer performed yeoman service keeping the obsolete turbine operational.", "workplace"),
    (577, "zeugma", "/ˈzuːɡmə/", "noun", "phép ngỗ kết (tu từ ghép nghĩa)", "The clever lyricist employed zeugma in 'She broke his car keys and his fragile heart.'", "rhetoric"),
    (578, "apocryphal", "/əˈpɑːkrɪfl/", "adjective", "ngụy thư, truyền khẩu không xác thực", "The amusing anecdote regarding Newton and the falling apple is largely apocryphal.", "history"),
    (579, "bathyal", "/ˈbæθiəl/", "adjective", "thuộc về vùng nước sâu đại dương", "Bioluminescent predators inhabit the pitch-black bathyal depths of the abyssal plain.", "oceanography"),
    (580, "clandestine", "/klænˈdestɪn/", "adjective", "bí mật phi pháp, lén lút", "The counter-intelligence unit intercepted clandestine radio transmissions across the border.", "espionage"),
    (581, "demagogue", "/ˈdeməɡɑːɡ/", "noun", "kẻ mị dân xảo trá", "The unscrupulous demagogue exploited public fear to consolidate tyrannical power.", "politics"),
    (582, "erudite", "/ˈerudaɪt/", "adjective", "uyên bác, bác học thông tuệ", "The keynote speaker offered an erudite critique of late-Hellenistic philosophy.", "academic"),
    (583, "fiduciary", "/fɪˈduːʃieri/", "adjective", "thuộc trách nhiệm ủy thác, tín thác", "Corporate trustees are bound by strict fiduciary obligations to company shareholders.", "law"),
    (584, "glib", "/ɡlɪb/", "adjective", "lém lỉnh sáo rỗng, nông cạn", "Voters saw through the candidate's glib soundbites and demanded concrete policies.", "politics"),
    (585, "heterodox", "/ˈhetərədɑːks/", "adjective", "dị giáo, không chính thống khác biệt", "The maverick economist published a bold, heterodox paper challenging central banking norms.", "economics"),
    (586, "imprimatur", "/ˌɪmprɪˈmɑːtər/", "noun", "sự phê chuẩn chính thức, dấu bảo chứng", "The scholarly monograph received the coveted imprimatur of the Oxford University Press.", "publishing"),
    (587, "jurisprudence", "/ˌdʒʊrɪsˈpruːdns/", "noun", "khoa học pháp lý, án lệ học", "Her seminal treatise reshaped constitutional jurisprudence concerning civil liberties.", "law"),
    (588, "kudos", "/ˈkuːdoʊs/", "noun", "vinh dự, lời khen ngợi tán dương", "The courageous whistle-blower received international kudos for uncovering environmental fraud.", "society"),
    (589, "lionize", "/ˈlaɪənaɪz/", "verb", "tôn sùng như vĩ nhân", "Biographers should balance the temptation to lionize historical figures with objective scrutiny.", "history"),
    (590, "mendacious", "/menˈdeɪʃəs/", "adjective", "dối trá xảo quyệt, sai sự thật", "The court levied severe contempt fines against the brazenly mendacious witness.", "law"),
    (591, "nugatory", "/ˈnuːɡətɔːri/", "adjective", "vô giá trị, không có hiệu lực", "The treaty clause proved nugatory once enforcement mechanisms were stripped away.", "diplomacy"),
    (592, "oleaginous", "/ˌoʊliˈædʒɪnəs/", "adjective", "nịnh nọt giả tạo / nhờn bóng", "His oleaginous flatteries failed to curry favor with the no-nonsense hiring panel.", "demeanor"),
    (593, "paripatetic", "/ˌperɪpəˈtetɪk/", "adjective", "nay đây mai đó, lữ hành", "The peripatetic ethnographer spent decades living alongside nomadic pastoralists.", "anthropology"),
    (594, "quislingism", "/ˈkwɪzlɪŋɪzəm/", "noun", "hành vi phản bội tiếp tay cho giặc", "The tribunal investigated wartime civil administrators implicated in state quislingism.", "history"),
    (595, "raconteur", "/ˌrækɑːnˈtɜːr/", "noun", "người kể chuyện duyên dáng lôi cuốn", "The charismatic novelist was an incomparable raconteur at salon literary dinners.", "literature"),
    (596, "stentorian", "/stenˈtɔːriən/", "adjective", "vang dội như sấm truyền", "The drill sergeant issued marching orders in a stentorian voice that echoed across the field.", "military"),
    (597, "tessellated", "/ˈtesəleɪtɪd/", "adjective", "khảm hoa văn hình học đều đặn", "The Roman bathhouse was paved with exquisite tessellated geometric mosaic stones.", "archaeology"),
    (598, "uxoriousness", "/ʌkˈsɔːriəsnəs/", "noun", "tính si mê chiều chuộng vợ tuyệt đối", "Court chroniclers noted the emperor's legendary uxoriousness with quiet amusement.", "history"),
    (599, "vociferousness", "/voʊˈsɪfərəsnəs/", "noun", "sự hò hét lớn tiếng, phản kháng ầm ĩ", "The vociferousness of the university protest startled municipal city hall.", "politics"),
    (600, "weltschmerz", "/ˈveltˌʃmerts/", "noun", "nỗi u sầu thế sự, nỗi đau nhân thế", "Romantic poets distilled existential weltschmerz into sublime, brooding verses.", "philosophy")
]

# Generate data/vocabulary.js
js_content = "const VOCABULARY_DATA = {\n"

for lvl_name, words in [("A1", a1_words), ("A2", a2_words), ("B1", b1_words), ("B2", b2_words), ("C1", c1_words), ("C2", c2_words)]:
    js_content += f"  {lvl_name}: [\n"
    for w in words:
        item = {
            "id": w[0],
            "word": w[1],
            "phonetic": w[2],
            "type": w[3],
            "meaning": w[4],
            "example": w[5],
            "topic": w[6]
        }
        js_content += "    " + json.dumps(item, ensure_ascii=False) + ",\n"
    js_content += "  ],\n"

js_content += "};\n"

with open("data/vocabulary.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"Successfully generated data/vocabulary.js with {len(a1_words) + len(a2_words) + len(b1_words) + len(b2_words) + len(c1_words) + len(c2_words)} entries!")
print(f"A1: {len(a1_words)}, A2: {len(a2_words)}, B1: {len(b1_words)}, B2: {len(b2_words)}, C1: {len(c1_words)}, C2: {len(c2_words)}")
